module.exports = {
  apps: [
    {
      name: "bun-app",
      script: "index.ts",
      interpreter: "bun",
      env: {
        PORT: process.env.PORT,
        TOKEN: process.env.TOKEN,
        apiKey: process.env.apiKey,
        authDomain: process.env.authDomain,
        projectId: process.env.projectId,
        storageBucket: process.env.storageBucket,
        messagingSenderId: process.env.messagingSenderId,
        appId: process.env.appId,
        measurementId: process.env.measurementId,
        DB_URI: process.env.DB_URI,
        AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
        AWS_REGION: process.env.AWS_REGION,
        stripe_access_key: process.env.stripe_access_key,
        stripe_secret_key: process.env.stripe_secret_key,
        stripe_webhook_endpoint_secret:
          process.env.stripe_webhook_endpoint_secret,
        getstream_io_key: process.env.getstream_io_key,
        getstream_io_secret: process.env.getstream_io_secret,
        email: process.env.email,
        password: process.env.password,
        FRONTEND_URL: process.env.FRONTEND_URL,
        REDIES_HOST: process.env.REDIES_HOST,
        REDIES_PORT: process.env.REDIES_PORT,
        REDIES_PASSWORD: process.env.REDIES_PASSWORD,
      },
    },
  ],
};
