module.exports = {
  apps: [
    {
      name: "bun-app",
      script: "index.ts",
      interpreter: "bun",
      env: {
        PORT: process.env.PORT,
        TOKEN: process.env.TOKEN,
        apiKey: process.env.apiKey,
        authDomain: process.env.authDomain,
        projectId: process.env.projectId,
        storageBucket: process.env.storageBucket,
        messagingSenderId: process.env.messagingSenderId,
        appId: process.env.appId,
        measurementId: process.env.measurementId,
        DB_URI: process.env.DB_URI,
        AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
        AWS_REGION: process.env.AWS_REGION,
        stripe_access_key: process.env.stripe_access_key,
        stripe_secret_key: process.env.stripe_secret_key,
        stripe_webhook_endpoint_secret:
          process.env.stripe_webhook_endpoint_secret,
        getstream_io_key: process.env.getstream_io_key,
        getstream_io_secret: process.env.getstream_io_secret,
        email: process.env.email,
        password: process.env.password,
        FRONTEND_URL: process.env.FRONTEND_URL,
        REDIES_HOST: process.env.REDIES_HOST,
        REDIES_PORT: process.env.REDIES_PORT,
        REDIES_PASSWORD: process.env.REDIES_PASSWORD,
        EMAIL: process.env.EMAIL,
        EMAIL_PASSWORD: process.env.EMAIL_PASSWORD,
        RAZORPAY_KEY: process.env.RAZORPAY_KEY,
        RAZORPAY_SECRET: process.env.RAZORPAY_SECRET,
        RAZORPAY_WEBHOOK_SECRET: process.env.RAZORPAY_WEBHOOK_SECRET,
        CLIENT_ID: process.env.CLIENT_ID,
        CLINET_SECRET: process.env.CLINET_SECRET,
        REFRESH_TOKEN: process.env.REFRESH_TOKEN,
        REDIRECT_URL: process.env.REDIRECT_URL,
        TECH_SUPPORT_EMAIL: process.env.TECH_SUPPORT_EMAIL,
        FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
        FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL,
        FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY,
        FIREBASE_DATABASE_URL: process.env.FIREBASE_DATABASE_URL,
      },
    },
  ],
};
