/**
 * Phase 19 — Live production path inventory (code-backed).
 */

import type { ProductionPathEntry } from "./types";

/**
 * Authoritative inventory from live entry points → AI Core / legacy spine.
 * Does not claim Action Execution is the sole HTTP ingress (strangler).
 */
export const PRODUCTION_PATH_INVENTORY: readonly ProductionPathEntry[] = [
  {
    pathId: "web_mobile_chat",
    surface: "web+mobile /chat",
    entry: "routes/chat.route.ts → chat.controller → service AI resolve-turn / executions",
    actionResolution: "CTI / service conversational resolve (legacy) or Action Registry when canonical",
    actionExecution: "POST /v1/executions → DirectExecutionEngine (primary); Action Execution when callers use it",
    contextOrchestration: "execution-create-prepass → orchestrateCanonicalGenerationContext (flag)",
    cmr: "Flag ON: CMR via apply; Flag OFF: skipped",
    modelRuntime: "Flag ON: prepareCanonicalModelRuntime; Flag OFF: legacy prompt path",
    provider: "DirectExecutionEngine Controllable/live dispatcher",
    outputQa: "Optional Phase 16 validateCanonicalActionOutput (caller)",
    repair: "Optional Phase 17 attemptCanonicalRepair (policy+env)",
    persistence: "tryIngest* Completions + artifact createVersion",
    stateAdvancement: "CDF transition approve/select (caller-gated; not auto by QA)",
    classification: "INTENTIONALLY_LEGACY",
    notes: "Shared Express surface for web and mobile; strangler alongside Direct spine",
  },
  {
    pathId: "execution_create",
    surface: "POST /v1/executions",
    entry: "execution-create-pipeline → prepass → dispatch → DirectExecutionEngine",
    actionResolution: "Capability / CTI / CDF metadata (not always Action Registry)",
    actionExecution: "DirectExecutionEngine (INTENTIONALLY_LEGACY spine)",
    contextOrchestration: "orchestrateCanonicalGenerationContext when flag+session+phase",
    cmr: "Canonical when flag ON",
    modelRuntime: "Canonical when flag ON",
    provider: "DirectExecutionEngine",
    outputQa: "Not auto-wired on HTTP create (opt-in)",
    repair: "Not auto-wired on HTTP create (opt-in)",
    persistence: "execution-create-dispatch ingest bridges (presentation/packaging/social)",
    stateAdvancement: "Separate CDF transition API",
    classification: "CANONICAL",
    notes: "Canonical context strangler on Direct path when flag ON",
  },
  {
    pathId: "cdf_transition",
    surface: "POST /v1/cdf/transition",
    entry: "dispatch → executeCdfActionAsync / applyCdfTransition",
    actionResolution: "CDF state machine actions; Action Registry mirrors as cdf.transition.*",
    actionExecution: "executeCdfAction / Action Execution STATE_TRANSITION mode",
    contextOrchestration: "N/A for pure transitions",
    cmr: "N/A",
    modelRuntime: "N/A",
    provider: "N/A",
    outputQa: "Shape checks via Output QA when Action Execution used",
    repair: "N/A for transitions",
    persistence: "session CAS + artifact select/approve",
    stateAdvancement: "Authoritative CDF SM",
    classification: "CANONICAL",
  },
  {
    pathId: "presentation_generation",
    surface: "presentation runtime",
    entry: "CDF phases + tryIngestPresentationCdfCompletion",
    actionResolution: "cdf.phase.presentation.*.generate|configure|materialize",
    actionExecution: "Direct create + Action Execution MODEL_GENERATION when used",
    contextOrchestration: "Orchestrator when flag ON",
    cmr: "Structured upstream ArtifactVersions",
    modelRuntime: "Canonical when flag ON",
    provider: "Direct / ControllableDispatcher in tests",
    outputQa: "validatePresentationArtifactData via Output QA",
    repair: "Bounded opt-in",
    persistence: "ArtifactVersion + session pins",
    stateAdvancement: "approve/select transitions",
    classification: "CANONICAL",
  },
  {
    pathId: "packaging_generation",
    surface: "packaging runtime",
    entry: "tryIngestPackagingCdfCompletion",
    actionResolution: "cdf.phase.packaging.*.generate",
    actionExecution: "Direct + Action Execution",
    contextOrchestration: "Orchestrator when flag ON",
    cmr: "Exact upstream pins",
    modelRuntime: "Canonical when flag ON",
    provider: "Direct",
    outputQa: "validatePackagingArtifactData",
    repair: "Bounded opt-in",
    persistence: "ArtifactVersion",
    stateAdvancement: "CDF transitions",
    classification: "CANONICAL",
  },
  {
    pathId: "social_media_generation",
    surface: "social-media runtime",
    entry: "tryIngestSocialMediaCdfCompletion",
    actionResolution: "cdf.phase.social-media.*.generate",
    actionExecution: "Direct + Action Execution",
    contextOrchestration: "Orchestrator when flag ON",
    cmr: "Exact upstream pins",
    modelRuntime: "Canonical when flag ON",
    provider: "Direct",
    outputQa: "validateSocialMediaArtifactData",
    repair: "Bounded opt-in",
    persistence: "ArtifactVersion",
    stateAdvancement: "CDF transitions",
    classification: "CANONICAL",
  },
  {
    pathId: "class_d_generation",
    surface: "12 Class-D services",
    entry: "CDF phases without deep ingest",
    actionResolution: "cdf.phase.<service>.*.generate registered",
    actionExecution: "Direct legacy notes path common",
    contextOrchestration: "May run when flag ON but continuity incomplete",
    cmr: "No deep ArtifactVersion continuity",
    modelRuntime: "Possible without claiming continuity",
    provider: "Direct",
    outputQa: "UNSUPPORTED_VALIDATION where continuity incomplete",
    repair: "Must not convert UNSUPPORTED→VALID",
    persistence: "Legacy / incomplete",
    stateAdvancement: "CDF SM without artifact-complete claims",
    classification: "UNSUPPORTED",
    notes: "artifactContinuityComplete: false",
  },
  {
    pathId: "refinement",
    surface: "CDF refine + OS refinements",
    entry: "refinement services + createVersion CAS",
    actionResolution: "cdf refine / Action refinement type",
    actionExecution: "Direct + refinement services",
    contextOrchestration: "Flag ON: resolver refinement + ActiveBrief",
    cmr: "When flag ON",
    modelRuntime: "When generation",
    provider: "Direct",
    outputQa: "Schema validators",
    repair: "Opt-in",
    persistence: "createVersion + requestId idempotency",
    stateAdvancement: "Session pins",
    classification: "CANONICAL",
  },
  {
    pathId: "selection_approval",
    surface: "CDF select/approve",
    entry: "applyCdfTransition select|approve",
    actionResolution: "cdf.transition.* / configure",
    actionExecution: "STATE_TRANSITION / artifact markSelected|markApproved",
    contextOrchestration: "N/A",
    cmr: "N/A",
    modelRuntime: "Must NOT invoke",
    provider: "N/A",
    outputQa: "Shape checks",
    repair: "N/A",
    persistence: "Session + artifact status",
    stateAdvancement: "Authoritative",
    classification: "CANONICAL",
  },
  {
    pathId: "render_materialize_export",
    surface: "CDF render / materialize / export",
    entry: "POST /v1/cdf/artifacts/.../render; .materialize actions",
    actionResolution: "RENDER_EXPORT / materialize",
    actionExecution: "executeRenderExportAction / CDF materialize",
    contextOrchestration: "N/A",
    cmr: "N/A",
    modelRuntime: "Must NOT invoke for deterministic materialize",
    provider: "Renderers only",
    outputQa: "Render identity shape",
    repair: "N/A",
    persistence: "Rendered files / export artifacts",
    stateAdvancement: "Final phases",
    classification: "CANONICAL",
  },
];

export function listProductionPaths(): readonly ProductionPathEntry[] {
  return PRODUCTION_PATH_INVENTORY;
}

export function getProductionPath(
  pathId: string,
): ProductionPathEntry | undefined {
  return PRODUCTION_PATH_INVENTORY.find((p) => p.pathId === pathId);
}
