/**
 * M9B — Social Media generation → canonical artifact boundary.
 *
 * When metadata carries cdfExecutionStrategy=canonical (or forceOptIn), ingest is mandatory.
 * Env CDF_SOCIAL_MEDIA_INGEST=1|true enables ingest for non-contract traffic.
 * FORCE_LEGACY kill-switches were removed — they re-enabled parallel legacy completion.
 *
 * Failure → fail-closed metadata (no silent success substitute). Never invents ArtifactVersion.
 */

import {
  SOCIAL_MEDIA_ARTIFACT_KEYS,
  SOCIAL_MEDIA_PHASE_ARTIFACT_KEY,
  type SocialMediaArtifactKey,
} from "../artifacts/social-media/keys";
import { getCdfSession } from "../session-store";
import { collectContractUpstreamRefs } from "../canonical-ingest/upstream-projection";
import {
  ingestGenerationCompletion,
  CdfGenerationArtifactError,
} from "../generation-artifact";
import { resolveArtifactTarget } from "../generation-artifact/target-resolution";
import type {
  IngestGenerationInput,
  IngestGenerationResult,
} from "../generation-artifact/types";
import { isM4AcceptanceStatus } from "../generation-validation";
import {
  findSocialMediaExactRef,
} from "./session-bind";

export const CDF_SOCIAL_MEDIA_RUNTIME_VERSION = "m9b.social_media.generation.v1";

export type SocialMediaCanonicalAttach = {
  cdfArtifactId: string;
  cdfArtifactVersion: number;
  cdfArtifactKey: string;
  cdfValidationStatus: string;
  cdfValidationId?: string;
  cdfRuntimePath: "canonical";
  cdfRuntimeVersion: string;
  canonicalPath: true;
  /** Always true on accepted attach — canonical download is default. */
  cdfDownloadEligible: boolean;
  cdfPreferLegacyDownload?: boolean;
};

export type SocialMediaIngestFailure = {
  kind:
    | "validation_failed"
    | "dependency_missing"
    | "ingest_failed"
    | "canonicalization_unsupported"
    | "opt_in_disabled"
    | "final_no_artifact";
  cdfValidationStatus?: string;
  cdfValidationId?: string;
  cdfRuntimePath: "none";
  legacyCompatible: true;
  fallbackReason: string;
  message: string;
};

export type TryIngestSocialMediaResult =
  | {
      kind: "accepted";
      ingest: IngestGenerationResult;
      attach: SocialMediaCanonicalAttach;
    }
  | SocialMediaIngestFailure
  | null;

function metaString(
  metadata: Record<string, unknown> | undefined,
  key: string,
): string | undefined {
  const v = metadata?.[key];
  return typeof v === "string" && v.trim() ? v.trim() : undefined;
}

/** Opt-in gate for non-contract traffic. Canonical contract callers pass forceOptIn. */
export function isSocialMediaCanonicalIngestEnabled(): boolean {
  return (
    process.env.CDF_SOCIAL_MEDIA_INGEST === "1" ||
    process.env.CDF_SOCIAL_MEDIA_INGEST === "true"
  );
}

function findExactRef(
  sessionId: string,
  artifactKey: SocialMediaArtifactKey,
): { artifactId: string; version: number } | undefined {
  const session = getCdfSession(sessionId);
  if (!session) return undefined;
  // Generation pins: selected_or_approved only — never silent generated bypass.
  return findSocialMediaExactRef(session, artifactKey, "selected_or_approved");
}

export function resolveSocialMediaRefsFromSession(
  sessionId: string,
): NonNullable<IngestGenerationInput["socialMediaRefs"]> {
  return {
    platformRef: findExactRef(sessionId, SOCIAL_MEDIA_ARTIFACT_KEYS.platform),
    sizeReferenceRef: findExactRef(
      sessionId,
      SOCIAL_MEDIA_ARTIFACT_KEYS.sizeReference,
    ),
    routesRef: findExactRef(sessionId, SOCIAL_MEDIA_ARTIFACT_KEYS.routes),
  };
}

/**
 * Attempt Social Media canonical ingest. Never throws to callers.
 * Returns null when metadata is not a Social Media CDF completion.
 */
export function tryIngestSocialMediaCdfCompletion(input: {
  metadata?: Record<string, unknown>;
  rawOutput: unknown;
  executionId?: string;
  organizationId?: string;
  workspaceId?: string;
  projectId?: string;
  userId?: string;
  vaultAssetIds?: string[];
  socialMediaRefs?: IngestGenerationInput["socialMediaRefs"];
  /** Test override — ignore env gate. */
  forceOptIn?: boolean;
}): TryIngestSocialMediaResult {
  const metadata = input.metadata;
  const sessionId = metaString(metadata, "cdfSessionId");
  const phaseId = metaString(metadata, "cdfPhaseId");
  const serviceRaw =
    metaString(metadata, "cdfServiceId") ||
    metaString(metadata, "service") ||
    "";
  const serviceNorm = serviceRaw.trim().toLowerCase();
  const isSocial =
    serviceNorm === "social-media" ||
    serviceNorm === "social media" ||
    serviceNorm === "social";

  if (!sessionId || !phaseId || !isSocial) {
    return null;
  }

  if (!input.forceOptIn && !isSocialMediaCanonicalIngestEnabled()) {
    return {
      kind: "opt_in_disabled",
      cdfRuntimePath: "none",
      legacyCompatible: true,
      fallbackReason: "opt_in_disabled",
      message:
        "CDF_SOCIAL_MEDIA_INGEST is off — Social Media live traffic remains legacy (M9B)",
    };
  }

  if (phaseId === "final" || SOCIAL_MEDIA_PHASE_ARTIFACT_KEY[phaseId] === null) {
    console.info(
      JSON.stringify({
        scope: "cdf.social_media_runtime",
        event: "final_no_artifact",
        sessionId,
        phaseId,
        canonicalPath: false,
        ts: new Date().toISOString(),
      }),
    );
    return {
      kind: "final_no_artifact",
      cdfRuntimePath: "none",
      legacyCompatible: true,
      fallbackReason: "final_no_artifact",
      message: "social-media.final has no creative schema",
    };
  }

  const session = getCdfSession(sessionId);
  if (!session) {
    return {
      kind: "ingest_failed",
      cdfRuntimePath: "none",
      legacyCompatible: true,
      fallbackReason: "session_missing",
      message: `CDF session not found: ${sessionId}`,
    };
  }

  let target;
  try {
    target = resolveArtifactTarget({ serviceId: "social-media", phaseId });
  } catch {
    return {
      kind: "ingest_failed",
      cdfRuntimePath: "none",
      legacyCompatible: true,
      fallbackReason: "target_unresolved",
      message: `No Social Media artifact mapping for phase ${phaseId}`,
    };
  }

  const socialMediaRefs =
    input.socialMediaRefs ?? resolveSocialMediaRefsFromSession(sessionId);

  const sourceArtifacts: Array<{
    artifactId: string;
    version: number;
    artifactKey: string;
    relationship: "uses";
  }> = [];
  const pushRef = (
    key: SocialMediaArtifactKey,
    ref: { artifactId: string; version: number } | undefined,
  ) => {
    if (!ref) return;
    sourceArtifacts.push({
      artifactId: ref.artifactId,
      version: ref.version,
      artifactKey: key,
      relationship: "uses",
    });
  };
  pushRef(SOCIAL_MEDIA_ARTIFACT_KEYS.platform, socialMediaRefs.platformRef);
  pushRef(
    SOCIAL_MEDIA_ARTIFACT_KEYS.sizeReference,
    socialMediaRefs.sizeReferenceRef,
  );
  pushRef(SOCIAL_MEDIA_ARTIFACT_KEYS.routes, socialMediaRefs.routesRef);

  try {
    const ingest = ingestGenerationCompletion({
      sessionId,
      serviceId: "social-media",
      phaseId,
      organizationId: input.organizationId ?? session.organizationId,
      workspaceId: input.workspaceId ?? session.workspaceId,
      projectId: input.projectId ?? session.projectId,
      userId: input.userId ?? session.userId,
      executionId: input.executionId,
      rawOutput: input.rawOutput,
      contextId: metaString(metadata, "cdfContextId"),
      contextHash: metaString(metadata, "cdfContextHash"),
      activeBriefId: session.activeBriefId,
      activeBriefVersion: session.activeBriefVersion,
      expectedSessionVersion: session.sessionVersion,
      socialMediaRefs,
      vaultAssetIds: input.vaultAssetIds,
      upstreamArtifactRefs: collectContractUpstreamRefs({ sessionId, serviceId, phaseId }),
      sourceArtifacts: sourceArtifacts.length ? sourceArtifacts : undefined,
      requestId: input.executionId
        ? `m9b_ingest_${input.executionId}_${phaseId}`
        : undefined,
      requireAcceptanceGate: true,
    });

    const status = ingest.validationStatus ?? "passed";
    if (
      !isM4AcceptanceStatus(
        status as "passed" | "review_required" | "failed",
      )
    ) {
      return {
        kind: "validation_failed",
        cdfValidationStatus: status,
        cdfValidationId: ingest.validationId,
        cdfRuntimePath: "none",
        legacyCompatible: true,
        fallbackReason: "m4_validation_failed",
        message: `M4 status ${status} — no canonical Social Media artifact`,
      };
    }

    const attach: SocialMediaCanonicalAttach = {
      cdfArtifactId: ingest.artifactId,
      cdfArtifactVersion: ingest.artifactVersion,
      cdfArtifactKey: ingest.artifactKey,
      cdfValidationStatus: status,
      cdfValidationId: ingest.validationId,
      cdfRuntimePath: "canonical",
      cdfRuntimeVersion: CDF_SOCIAL_MEDIA_RUNTIME_VERSION,
      canonicalPath: true,
      // Canonical attach always authorizes M5 download — no art_* strangler.
      cdfDownloadEligible: true,
    };

    // M9B ends at ArtifactVersion + return identity.
    // Do NOT mutate session.generatedArtifacts / selectedArtifacts / approvedArtifacts.
    // M9C bindSocialMediaGeneratedFromAttach consumes this attach (dispatch / callers).

    console.info(
      JSON.stringify({
        scope: "cdf.social_media_runtime",
        event: "ingest_accepted",
        sessionId,
        phaseId,
        artifactId: ingest.artifactId,
        artifactVersion: ingest.artifactVersion,
        artifactKey: ingest.artifactKey,
        artifactTargetKey: target.artifactKey,
        validationStatus: status,
        generationExecutionId: input.executionId,
        sessionMutation: false,
        canonicalPath: true,
        legacyFallback: false,
        downloadEligible: true,
        liveTrafficMigrated: true,
        ts: new Date().toISOString(),
      }),
    );

    return { kind: "accepted", ingest, attach };
  } catch (err) {
    if (
      err instanceof CdfGenerationArtifactError &&
      (err.generationArtifactCode === "SOCIAL_CANONICALIZATION_UNSUPPORTED" ||
        err.generationArtifactCode === "SOCIAL_STRUCTURED_DATA_MISSING" ||
        err.generationArtifactCode === "SOCIAL_VAULT_ASSET_MISSING" ||
        err.generationArtifactCode === "SOCIAL_PROVIDER_OUTPUT_INVALID")
    ) {
      return {
        kind: "canonicalization_unsupported",
        cdfRuntimePath: "none",
        legacyCompatible: true,
        fallbackReason: err.generationArtifactCode.toLowerCase(),
        message: err.message,
      };
    }
    if (
      err instanceof CdfGenerationArtifactError &&
      err.generationArtifactCode === "ARTIFACT_VALIDATION_FAILED"
    ) {
      const meta = err.metadata ?? {};
      return {
        kind: "validation_failed",
        cdfValidationStatus: String(meta.validationStatus ?? "failed"),
        cdfValidationId:
          typeof meta.validationId === "string" ? meta.validationId : undefined,
        cdfRuntimePath: "none",
        legacyCompatible: true,
        fallbackReason: "m4_validation_failed",
        message: err.message,
      };
    }
    if (
      err instanceof CdfGenerationArtifactError &&
      (err.generationArtifactCode === "ARTIFACT_DEPENDENCY_MISSING" ||
        err.generationArtifactCode === "SOCIAL_UPSTREAM_ARTIFACT_MISSING" ||
        err.generationArtifactCode === "SOCIAL_UPSTREAM_VERSION_MISSING")
    ) {
      return {
        kind: "dependency_missing",
        cdfRuntimePath: "none",
        legacyCompatible: true,
        fallbackReason: "social_dependency_missing",
        message: err.message,
      };
    }
    console.info(
      JSON.stringify({
        scope: "cdf.social_media_runtime",
        event: "ingest_failed_legacy_continues",
        sessionId,
        phaseId,
        canonicalPath: false,
        fallbackReason: "ingest_error",
        error: err instanceof Error ? err.message : String(err),
        ts: new Date().toISOString(),
      }),
    );
    return {
      kind: "ingest_failed",
      cdfRuntimePath: "none",
      legacyCompatible: true,
      fallbackReason: "ingest_error",
      message: err instanceof Error ? err.message : String(err),
    };
  }
}
