/**
 * AI accounting status enums.
 */

export const AI_COST_STATUS = {
  CALCULATED: "CALCULATED",
  PENDING_PRICING: "PENDING_PRICING",
  PENDING_PROVIDER_USAGE: "PENDING_PROVIDER_USAGE",
  PENDING_CONVERSION: "PENDING_CONVERSION",
  RECONCILED: "RECONCILED",
  DISCREPANCY: "DISCREPANCY",
  NON_BILLABLE: "NON_BILLABLE",
} as const;

export type AICostStatus = (typeof AI_COST_STATUS)[keyof typeof AI_COST_STATUS];

export const AI_USAGE_INVOCATION_STATUS = {
  SUCCEEDED: "SUCCEEDED",
  FAILED: "FAILED",
} as const;

export type AIUsageInvocationStatus =
  (typeof AI_USAGE_INVOCATION_STATUS)[keyof typeof AI_USAGE_INVOCATION_STATUS];

export const BILLING_RECONCILIATION_STATUS = {
  MATCHED: "MATCHED",
  UNMATCHED: "UNMATCHED",
  VARIANCE: "VARIANCE",
  AGGREGATE: "AGGREGATE",
  PENDING: "PENDING",
} as const;

export type BillingReconciliationStatus =
  (typeof BILLING_RECONCILIATION_STATUS)[keyof typeof BILLING_RECONCILIATION_STATUS];

export const PROJECTION_STATUS = {
  INSUFFICIENT_DATA: "INSUFFICIENT_DATA",
  NO_USAGE: "NO_USAGE",
  PROJECTED: "PROJECTED",
} as const;

export type ProjectionStatus =
  (typeof PROJECTION_STATUS)[keyof typeof PROJECTION_STATUS];

export const PRICING_UNIT = {
  TOKEN_INPUT_PER_1M: "TOKEN_INPUT_PER_1M",
  TOKEN_OUTPUT_PER_1M: "TOKEN_OUTPUT_PER_1M",
  TOKEN_CACHED_INPUT_PER_1M: "TOKEN_CACHED_INPUT_PER_1M",
  TOKEN_CACHED_OUTPUT_PER_1M: "TOKEN_CACHED_OUTPUT_PER_1M",
  TOKEN_REASONING_PER_1M: "TOKEN_REASONING_PER_1M",
  IMAGE: "IMAGE",
  VIDEO_SECOND: "VIDEO_SECOND",
  AUDIO_CHARACTER: "AUDIO_CHARACTER",
  AUDIO_SECOND: "AUDIO_SECOND",
  REQUEST: "REQUEST",
  EMBEDDING_TOKEN_PER_1M: "EMBEDDING_TOKEN_PER_1M",
} as const;

export type PricingUnit = (typeof PRICING_UNIT)[keyof typeof PRICING_UNIT];

export const REPORTING_CURRENCY = "USD" as const;
