/** Facebook field card — Format Spec p. 21. */

import { rule, srgbStill, videoWeb } from "./helpers";
import type { ProductionRule } from "../types";

export const FACEBOOK_RULES: readonly ProductionRule[] = Object.freeze([
  rule({
    id: "facebook.feed.square",
    platform: "facebook",
    subtype: "content-design",
    placement: "feed.square",
    status: "D",
    canvas: { width: 1080, height: 1080, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Separate exports, not two choices in one file.",
  }),
  rule({
    id: "facebook.feed.portrait",
    platform: "facebook",
    subtype: "content-design",
    placement: "feed.portrait",
    status: "D",
    canvas: { width: 1080, height: 1350, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Separate exports, not two choices in one file.",
  }),
  rule({
    id: "facebook.feed.landscape",
    platform: "facebook",
    subtype: "content-design",
    placement: "feed.landscape",
    status: "D",
    canvas: { width: 1080, height: 566, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Preview in feed and mobile crop.",
  }),
  rule({
    id: "facebook.carousel",
    platform: "facebook",
    subtype: "content-design",
    placement: "carousel",
    status: "D",
    canvas: { width: 1080, height: 1080, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Cover, cards and native commerce elements tested separately.",
  }),
  rule({
    id: "facebook.reels",
    platform: "facebook",
    subtype: "reels-stories",
    placement: "reels",
    status: "D",
    canvas: { width: 1080, height: 1920, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "15 s short-promo house default.",
  }),
  rule({
    id: "facebook.stories",
    platform: "facebook",
    subtype: "reels-stories",
    placement: "stories",
    status: "D",
    canvas: { width: 1080, height: 1920, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "15 s short-promo house default.",
  }),
  rule({
    id: "facebook.cover-photo",
    platform: "facebook",
    subtype: "content-design",
    placement: "cover-photo",
    status: "D",
    canvas: { width: 1640, height: 624, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "User-supplied working size; responsive crop check required.",
  }),
  rule({
    id: "facebook.group-cover",
    platform: "facebook",
    subtype: "content-design",
    placement: "group-cover",
    status: "D",
    canvas: { width: 1640, height: 856, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Keep essential content central.",
  }),
  rule({
    id: "facebook.event-cover",
    platform: "facebook",
    subtype: "content-design",
    placement: "event-cover",
    status: "D",
    canvas: { width: 1920, height: 1005, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Confirm event surface before export.",
  }),
  rule({
    id: "facebook.profile-picture",
    platform: "facebook",
    subtype: "content-design",
    placement: "profile-picture",
    status: "D",
    canvas: { width: 320, height: 320, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Inspect circular crop.",
  }),
  rule({
    id: "facebook.marketplace",
    platform: "facebook",
    subtype: "content-design",
    placement: "marketplace",
    status: "D",
    canvas: { width: 1200, height: 1200, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Accurate subject; no deceptive text.",
  }),
  rule({
    id: "facebook.instant-experience-cover",
    platform: "facebook",
    subtype: "content-design",
    placement: "instant-experience-cover",
    status: "R",
    canvas: { width: 1080, height: 1080, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Native destination uses its own configuration — confirm before production.",
  }),
  rule({
    id: "facebook.page-cover-video",
    platform: "facebook",
    subtype: "content-design",
    placement: "page-cover-video",
    status: "H",
    canvas: { width: 820, height: 462, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "Legacy supplied entry; confirm feature availability. Do not book as approved.",
  }),
]);
