/** Instagram field card — Format Spec p. 20. */

import { rule, srgbStill, videoWeb } from "./helpers";
import type { ProductionRule } from "../types";

export const INSTAGRAM_RULES: readonly ProductionRule[] = Object.freeze([
  rule({
    id: "instagram.feed.square",
    platform: "instagram",
    subtype: "content-design",
    placement: "feed.square",
    status: "D",
    canvas: { width: 1080, height: 1080, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "PNG/JPG; one message.",
  }),
  rule({
    id: "instagram.feed.portrait",
    platform: "instagram",
    subtype: "content-design",
    placement: "feed.portrait",
    status: "D",
    canvas: { width: 1080, height: 1350, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Default editorial master; not the only supported ratio.",
  }),
  rule({
    id: "instagram.feed.landscape",
    platform: "instagram",
    subtype: "content-design",
    placement: "feed.landscape",
    status: "D",
    canvas: { width: 1080, height: 566, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Recompose; do not stretch portrait art.",
  }),
  rule({
    id: "instagram.carousel",
    platform: "instagram",
    subtype: "content-design",
    placement: "carousel",
    status: "D",
    canvas: { width: 1080, height: 1350, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "One size throughout; square route is 1080×1080.",
  }),
  rule({
    id: "instagram.reels",
    platform: "instagram",
    subtype: "reels-stories",
    placement: "reels",
    status: "D",
    canvas: { width: 1080, height: 1920, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "MP4/PNG/JPG by content; preview UI overlays.",
  }),
  rule({
    id: "instagram.stories",
    platform: "instagram",
    subtype: "reels-stories",
    placement: "stories",
    status: "D",
    canvas: { width: 1080, height: 1920, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "MP4/PNG/JPG by content; preview UI overlays.",
  }),
  rule({
    id: "instagram.profile-picture",
    platform: "instagram",
    subtype: "content-design",
    placement: "profile-picture",
    status: "D",
    canvas: { width: 320, height: 320, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Circular crop test; full wordmark may be too small.",
  }),
  rule({
    id: "instagram.story-highlights",
    platform: "instagram",
    subtype: "content-design",
    placement: "story-highlights",
    status: "D",
    canvas: { width: 1080, height: 1080, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Center motif; inspect circular crop.",
  }),
]);
