/** LinkedIn field card — Format Spec p. 22. */

import { rule, srgbStill, videoWeb } from "./helpers";
import type { ProductionRule } from "../types";

export const LINKEDIN_RULES: readonly ProductionRule[] = Object.freeze([
  rule({
    id: "linkedin.organic.landscape",
    platform: "linkedin",
    subtype: "content-design",
    placement: "organic.landscape",
    status: "D",
    canvas: { width: 1200, height: 628, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Working preset; not an ad guarantee.",
  }),
  rule({
    id: "linkedin.organic.square",
    platform: "linkedin",
    subtype: "content-design",
    placement: "organic.square",
    status: "D",
    canvas: { width: 1080, height: 1080, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Readable mobile text.",
  }),
  rule({
    id: "linkedin.organic.portrait",
    platform: "linkedin",
    subtype: "content-design",
    placement: "organic.portrait",
    status: "D",
    canvas: { width: 1080, height: 1350, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Readable mobile text.",
  }),
  rule({
    id: "linkedin.document-pages",
    platform: "linkedin",
    subtype: "content-design",
    placement: "document-pages",
    status: "D",
    canvas: { width: 1080, height: 1350, unit: "px" },
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["pdf", "png", "jpg"]),
      notes: "Export PDF; same page size; keep text selectable.",
    }),
    productionNote: "Export PDF; same page size; keep text selectable.",
  }),
  rule({
    id: "linkedin.company-cover",
    platform: "linkedin",
    subtype: "content-design",
    placement: "company-cover",
    status: "D",
    canvas: { width: 1128, height: 191, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "User-supplied preset; preview crop.",
  }),
  rule({
    id: "linkedin.personal-banner",
    platform: "linkedin",
    subtype: "content-design",
    placement: "personal-banner",
    status: "D",
    canvas: { width: 1584, height: 396, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Keep profile-photo obstruction clear.",
  }),
  rule({
    id: "linkedin.event-cover",
    platform: "linkedin",
    subtype: "content-design",
    placement: "event-cover",
    status: "D",
    canvas: { width: 1776, height: 444, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Check upload preview.",
  }),
  rule({
    id: "linkedin.newsletter-cover",
    platform: "linkedin",
    subtype: "content-design",
    placement: "newsletter-cover",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Editorial working preset.",
  }),
  rule({
    id: "linkedin.video.vertical",
    platform: "linkedin",
    subtype: "content-design",
    placement: "video.vertical",
    status: "D",
    canvas: { width: 1080, height: 1920, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "Separate timeline compositions.",
  }),
  rule({
    id: "linkedin.video.square",
    platform: "linkedin",
    subtype: "content-design",
    placement: "video.square",
    status: "D",
    canvas: { width: 1080, height: 1080, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "Separate timeline compositions.",
  }),
  rule({
    id: "linkedin.video.landscape",
    platform: "linkedin",
    subtype: "content-design",
    placement: "video.landscape",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "Separate timeline compositions.",
  }),
  rule({
    id: "linkedin.ad.single-image.landscape",
    platform: "linkedin",
    subtype: "content-design",
    placement: "ad.single-image.landscape",
    status: "V",
    sourceRef: "[S3]",
    canvas: { width: 1200, height: 628, unit: "px" },
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["jpg", "png", "gif"]),
      notes: "JPG/PNG/GIF; 5 MB maximum.",
    }),
    productionNote: "Verified ad size — use only inside cited LinkedIn single-image ad scope.",
  }),
  rule({
    id: "linkedin.ad.single-image.square",
    platform: "linkedin",
    subtype: "content-design",
    placement: "ad.single-image.square",
    status: "V",
    sourceRef: "[S3]",
    canvas: { width: 1200, height: 1200, unit: "px" },
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["jpg", "png", "gif"]),
      notes: "Recommended square ad size.",
    }),
    productionNote: "Verified ad size — use only inside cited LinkedIn single-image ad scope.",
  }),
  rule({
    id: "linkedin.ad.single-image.portrait",
    platform: "linkedin",
    subtype: "content-design",
    placement: "ad.single-image.portrait",
    status: "V",
    sourceRef: "[S3]",
    canvas: { width: 720, height: 900, unit: "px" },
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["jpg", "png", "gif"]),
      notes: "4:5; vertical image ads deliver on mobile, not desktop.",
    }),
    productionNote: "Verified ad size — use only inside cited LinkedIn single-image ad scope.",
  }),
]);
