/**
 * Phase 2 — Service-default Format & Production Spec catalog (Services 01–15).
 * Covers every SERVICE_OUTPUT_MAP path; platform field cards remain in rules/*-platform files.
 * Hygiene Reference Edition 1.0 canvas/export conventions; no invented platform pixel cards.
 */

import { rule, srgbStill, videoWeb } from "./helpers";
import {
  ADS_HYGIENE,
  BRANDING_HYGIENE,
  EMAIL_HYGIENE,
  EVENT_HYGIENE,
  ILLUSTRATION_HYGIENE,
  MERCHANDISE_HYGIENE,
  PACKAGING_HYGIENE,
  PHOTOGRAPHY_HYGIENE,
  POS_HYGIENE,
  PRESENTATION_HYGIENE,
  PRINT_HYGIENE,
  SOCIAL_HYGIENE,
  STRATEGY_HYGIENE,
  VIDEO_HYGIENE,
  WEB_HYGIENE,
} from "./service-hygiene";
import type { ProductionRule } from "../types";

// —— Shared Admin QC checklists (family-level) ——

const socialBefore = Object.freeze([
  "Confirm objective, audience, channel, organic/paid placement, language, offer, CTA destination, publishing date and approved copy.",
  "Name the exact intended placement; never approve an asset for “All”.",
  "Check caption, link, cover, alt text and native CTA separately.",
]);

const socialHowTo = Object.freeze([
  "Use separate compositions for portrait, square and vertical; do not auto-stretch.",
  "Check current platform overlay and publishing preview before release.",
]);

const webBefore = Object.freeze([
  "Confirm business goal, sitemap, user journeys, content, devices, integrations, hosting, data collection, accessibility target and release owner.",
]);

const webHowTo = Object.freeze([
  "12-column desktop / 4-column mobile construction grid as guide starting point.",
  "Content must reflow; never simulate responsiveness by scaling a screenshot.",
  "Keep one primary action per screen.",
  "Use the approved accessibility test plan; automated checks alone are insufficient.",
]);

const brandingBefore = Object.freeze([
  "Confirm approved name, purpose, audience, personality, markets, usage contexts, naming restrictions and decision-maker.",
]);

const brandingHowTo = Object.freeze([
  "Use supplied artwork; never retype, stretch, trace or add effects.",
  "House clear-space proposal: at least 0.5 logo-height on every side.",
  "House minimum-size starting point: 180 px digital or 35 mm print wide.",
]);

const packagingBefore = Object.freeze([
  "Confirm measured dieline, SKU contents, substrate, print method, vendor tolerances, market, mandatory copy, barcode and approved product information.",
]);

const packagingHowTo = Object.freeze([
  "Create from approved vendor dieline at 1:1 — no generic canvas.",
  "Keep cut/fold guides non-printing and separate from live artwork.",
  "Approve a physical colour proof; screen appearance is not production colour approval.",
  "Scan barcode/QR from a printed proof at actual size before release.",
]);

const printBefore = Object.freeze([
  "Confirm final physical size, viewing distance, media site, material, finishing, installation, printer profile and approved copy.",
]);

const printHowTo = Object.freeze([
  "Declare width × height, units and working scale on every production file.",
  "Calculate effective image resolution at final physical size.",
  "Proof trim, bleed and live area during review.",
]);

const videoBefore = Object.freeze([
  "Confirm objective, audience, placement, script, storyboard, duration, frame rate, VO, music rights, captions and source-delivery needs.",
]);

const videoHowTo = Object.freeze([
  "Do not hardcode a universal frame rate; match the approved/source frame rate.",
  "Captions must be accurate and readable.",
  "Final QA: no stray frames, broken transitions, missing media or unwanted end black.",
]);

const presentationBefore = Object.freeze([
  "Confirm audience, decision sought, presentation context, source content, data evidence, slide count, presenter needs and editability.",
]);

const presentationHowTo = Object.freeze([
  "House legibility: titles 32 pt+, body 20 pt+, references 12 pt+; test projected view.",
  "One useful takeaway headline per slide.",
  "Keep charts and text editable when requested.",
]);

const emailBefore = Object.freeze([
  "Confirm audience, objective, sending system, subject, preheader, offer, landing page, personalization and approval requirements.",
]);

const emailHowTo = Object.freeze([
  "Keep essential message and CTA as live text/HTML; do not flatten the entire email into one image.",
  "House minimum body size: 16 px; button tap region: 44 px high.",
  "Test image-off, mobile and dark-mode views.",
]);

const posBefore = Object.freeze([
  "Confirm fixture measurements, store environment, offer terms, materials, mount method, safety clearances and supplier sample path.",
]);

const posHowTo = Object.freeze([
  "Match signed fixture measurements; keep artwork clear of hardware and concealed regions.",
  "Hierarchy: identity → main benefit → action, readable at a glance.",
  "Approve shopper-eye-level mockup, not just flat artwork.",
]);

const merchBefore = Object.freeze([
  "Confirm decoration method, garment/item specs, sizes, colours, placement side, brand artwork rights and sample approval path.",
]);

const merchHowTo = Object.freeze([
  "Design for the selected decoration method; do not auto-simplify or stretch the wordmark.",
  "State print size, orientation and garment/item side explicitly.",
  "Require a signed production sample before batch release.",
]);

const illustrationBefore = Object.freeze([
  "Confirm use case, style references, deliverable sizes, colour space, vector vs raster needs, originality constraints and source accuracy requirements.",
]);

const illustrationHowTo = Object.freeze([
  "Keep line weight, perspective, shading and palette consistent across the set.",
  "Deliver named layers and clean paths with no stray draft elements.",
  "Match raster resolution and vector delivery to intended use.",
]);

const photoBefore = Object.freeze([
  "Confirm shot list, product truth constraints, colour reference, rights (model/property), retouching limits and master vs crop delivery needs.",
]);

const photoHowTo = Object.freeze([
  "Do not alter product branding, claims, shape or functional details without approval.",
  "Inspect cutouts at 100%; no halos, clipped foreground or accidental transparency.",
  "Name masters and derivative crops; retain the full subject when requested.",
]);

const strategyBefore = Object.freeze([
  "Confirm decision owner, research inputs, audience priority, competitive context, success metrics and downstream creative brief owners.",
]);

const strategyHowTo = Object.freeze([
  "Link claims to actual research; clearly tag assumptions — never invent findings.",
  "Every recommendation must change a message, design choice or delivery plan.",
  "Require decision-owner sign-off before identity or campaign rollout.",
]);

const adsBefore = Object.freeze([
  "Confirm bought placement, offer, landing page, tracking parameters, creative variants, claims substantiation and pre-launch preview path.",
]);

const adsHowTo = Object.freeze([
  "Offer and CTA must match the landing page exactly.",
  "Treat native platform CTA separately; artwork text is not the interactive button.",
  "Preview in the bought placement before release.",
]);

const eventBefore = Object.freeze([
  "Confirm venue maps, screen/print dimensions, dates, speakers, agenda, wayfinding needs, safety clearances and onsite rehearsal plan.",
]);

const eventHowTo = Object.freeze([
  "Use confirmed venue screen maps and print dimensions — no assumed sizes.",
  "Use only approved dates, venue, speaker names and agenda.",
  "Design for onsite rehearsal of loops, playback, legibility and install.",
]);

const packagingExport = Object.freeze({
  formats: Object.freeze(["pdf"]),
  notes: "CMYK/spot per vendor; 1:1 dieline in mm — no fixed house canvas.",
});

const webDesktopExport = Object.freeze({
  formats: Object.freeze(["html", "zip", "png"]),
  notes: "1440×900 desktop design frames; also author 390 px mobile frames.",
});

const presentationExport = Object.freeze({
  formats: Object.freeze(["pptx", "pdf"]),
  notes: "16:9; 13.333 × 7.5 in house canvas.",
});

const emailExport = Object.freeze({
  formats: Object.freeze(["html", "png", "jpg"]),
  notes: "600 px content width; images at 2× displayed dimensions.",
});

const documentExport = Object.freeze({
  formats: Object.freeze(["pdf", "docx"]),
  notes: "Document deliverable; placement-appropriate canvas when visual pages are included.",
});

/** Service-level defaults used when no platform/format card matches. */
export const SERVICE_DEFAULT_RULES: readonly ProductionRule[] = Object.freeze([
  // —— Service 01 — Social Media ——
  rule({
    id: "social.strategy.default",
    service: "social",
    subtype: "strategy",
    placement: "default",
    status: "D",
    colour: "sRGB",
    export: documentExport,
    productionNote: "Structured channel plan; no fixed creative canvas.",
    beforeCreateChecks: socialBefore,
    howToCreate: Object.freeze([
      "Name exact placements and objectives per channel; never approve “All”.",
      "Separate organic vs paid recommendations and measurement owners.",
    ]),
    hygieneChecks: SOCIAL_HYGIENE,
  }),
  rule({
    id: "social.content-design.default",
    service: "social",
    subtype: "content-design",
    placement: "default",
    status: "D",
    canvas: { width: 1080, height: 1350, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "House editorial master 1080×1350 when placement is unspecified.",
    beforeCreateChecks: socialBefore,
    howToCreate: socialHowTo,
    hygieneChecks: SOCIAL_HYGIENE,
  }),
  rule({
    id: "social.copywriting.default",
    service: "social",
    subtype: "copywriting",
    placement: "default",
    status: "D",
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["txt", "docx"]),
      notes: "Captions, headlines, hashtags and CTAs; pair with placement asset when visual.",
    }),
    productionNote: "Copy deliverable; visual canvases follow placement cards.",
    beforeCreateChecks: socialBefore,
    howToCreate: Object.freeze([
      "Write for the named placement character limits and muted-first clarity.",
      "Treat caption, link and native CTA as separate deliverables.",
    ]),
    hygieneChecks: SOCIAL_HYGIENE,
  }),
  rule({
    id: "social.carousel.default",
    service: "social",
    subtype: "carousel",
    placement: "default",
    status: "D",
    canvas: { width: 1080, height: 1350, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "5-page house example at 1080×1350 per page; one ratio throughout.",
    beforeCreateChecks: socialBefore,
    howToCreate: Object.freeze([
      "Numbered page files + preview PDF.",
      "One size throughout the carousel.",
    ]),
    hygieneChecks: SOCIAL_HYGIENE,
  }),

  // —— Service 02 — Web Tech ——
  rule({
    id: "website.corporate-website.default",
    service: "website",
    subtype: "corporate-website",
    placement: "default",
    status: "D",
    canvas: { width: 1440, height: 900, unit: "px" },
    colour: "screen-rgb",
    export: webDesktopExport,
    beforeCreateChecks: webBefore,
    howToCreate: webHowTo,
    hygieneChecks: WEB_HYGIENE,
  }),
  rule({
    id: "website.ecom-website.default",
    service: "website",
    subtype: "ecom-website",
    placement: "default",
    status: "D",
    canvas: { width: 1440, height: 900, unit: "px" },
    colour: "screen-rgb",
    export: webDesktopExport,
    productionNote: "Commerce marketing site frames; product/cart states required.",
    beforeCreateChecks: webBefore,
    howToCreate: Object.freeze([
      ...webHowTo,
      "Include product, cart, error, loading and empty states.",
    ]),
    hygieneChecks: WEB_HYGIENE,
  }),
  rule({
    id: "website.landing-page.default",
    service: "website",
    subtype: "landing-page",
    placement: "default",
    status: "D",
    canvas: { width: 1440, height: 900, unit: "px" },
    colour: "screen-rgb",
    export: Object.freeze({
      formats: Object.freeze(["html", "zip", "png"]),
      notes: "1440×900 desktop + 390 px mobile; one campaign goal and primary CTA.",
    }),
    beforeCreateChecks: webBefore,
    howToCreate: Object.freeze([
      "One primary action per screen.",
      "Use the approved accessibility test plan; automated checks alone are insufficient.",
    ]),
    hygieneChecks: WEB_HYGIENE,
  }),
  rule({
    id: "website.ui-design.default",
    service: "website",
    subtype: "ui-design",
    placement: "default",
    status: "D",
    canvas: { width: 1440, height: 900, unit: "px" },
    colour: "screen-rgb",
    export: webDesktopExport,
    beforeCreateChecks: webBefore,
    howToCreate: webHowTo,
    hygieneChecks: WEB_HYGIENE,
  }),
  rule({
    id: "website.visual-asset.default",
    service: "website",
    subtype: "visual-asset",
    placement: "default",
    status: "D",
    canvas: { width: 1440, height: 900, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Clarify requirement then generate; prefer placement-appropriate size.",
    beforeCreateChecks: webBefore,
    howToCreate: Object.freeze([
      "Match intended web placement; do not invent platform pixel cards.",
      "Export sRGB stills suitable for the briefed use.",
    ]),
    hygieneChecks: WEB_HYGIENE,
  }),
  rule({
    id: "website.ux-strategy.default",
    service: "website",
    subtype: "ux-strategy",
    placement: "default",
    status: "D",
    colour: "screen-rgb",
    export: documentExport,
    productionNote: "Journeys and IA documentation; no fixed creative canvas.",
    beforeCreateChecks: webBefore,
    howToCreate: Object.freeze([
      "Document user journeys, information architecture and accessibility targets.",
      "Do not capture live user data until notices and consent are approved.",
    ]),
    hygieneChecks: WEB_HYGIENE,
  }),
  rule({
    id: "website.interactive-prototypes.default",
    service: "website",
    subtype: "interactive-prototypes",
    placement: "default",
    status: "D",
    canvas: { width: 1440, height: 900, unit: "px" },
    colour: "screen-rgb",
    export: webDesktopExport,
    beforeCreateChecks: webBefore,
    howToCreate: Object.freeze([
      ...webHowTo,
      "Include working links/forms paths with error, loading and empty states; support keyboard focus.",
    ]),
    hygieneChecks: WEB_HYGIENE,
  }),
  rule({
    id: "website.design-systems.default",
    service: "website",
    subtype: "design-systems",
    placement: "default",
    status: "D",
    canvas: { width: 1440, height: 900, unit: "px" },
    colour: "screen-rgb",
    export: Object.freeze({
      formats: Object.freeze(["pdf", "fig", "zip"]),
      notes: "UI kit, component library and usage documentation.",
    }),
    beforeCreateChecks: webBefore,
    howToCreate: Object.freeze([
      "Document components, tokens and usage rules with named variants.",
      "Meet the approved accessibility target across system examples.",
    ]),
    hygieneChecks: WEB_HYGIENE,
  }),
  rule({
    id: "website.app-development.default",
    service: "website",
    subtype: "app-development",
    placement: "default",
    status: "D",
    canvas: { width: 1440, height: 900, unit: "px" },
    colour: "screen-rgb",
    export: Object.freeze({
      formats: Object.freeze(["zip", "html"]),
      notes: "Resolved stack project with downloadable source.",
    }),
    beforeCreateChecks: webBefore,
    howToCreate: webHowTo,
    hygieneChecks: WEB_HYGIENE,
  }),
  rule({
    id: "website.other.default",
    service: "website",
    subtype: "other",
    placement: "default",
    status: "D",
    canvas: { width: 1440, height: 900, unit: "px" },
    colour: "screen-rgb",
    export: webDesktopExport,
    productionNote: "Catch-all web deliverable; clarify kind before production.",
    beforeCreateChecks: webBefore,
    howToCreate: webHowTo,
    hygieneChecks: WEB_HYGIENE,
  }),

  // —— Service 03 — Branding & Logo ——
  rule({
    id: "branding.logo-design.default",
    service: "branding",
    subtype: "logo-design",
    placement: "default",
    status: "D",
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["svg", "pdf", "png"]),
      notes: "SVG/PDF + transparent PNG at 2400×2400 px house vector export.",
    }),
    canvas: { width: 2400, height: 2400, unit: "px" },
    productionNote: "Vector master; black and reverse-white versions.",
    beforeCreateChecks: brandingBefore,
    howToCreate: brandingHowTo,
    hygieneChecks: BRANDING_HYGIENE,
  }),
  rule({
    id: "branding.visual-identity.default",
    service: "branding",
    subtype: "visual-identity",
    placement: "default",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["pptx", "pdf", "png"]),
      notes: "Identity presentation covering colour, type and visual language.",
    }),
    beforeCreateChecks: brandingBefore,
    howToCreate: Object.freeze([
      ...brandingHowTo,
      "Show colour palette, typography and applications with named versions.",
    ]),
    hygieneChecks: BRANDING_HYGIENE,
  }),
  rule({
    id: "branding.brand-guidelines.default",
    service: "branding",
    subtype: "brand-guidelines",
    placement: "default",
    status: "D",
    colour: "sRGB",
    export: documentExport,
    productionNote: "Brand standards document; include logo, colour, type and applications.",
    beforeCreateChecks: brandingBefore,
    howToCreate: Object.freeze([
      ...brandingHowTo,
      "Deliver named versions whose source and exports visually match.",
    ]),
    hygieneChecks: BRANDING_HYGIENE,
  }),
  rule({
    id: "branding.brand-naming-taglines.default",
    service: "branding",
    subtype: "brand-naming-taglines",
    placement: "default",
    status: "D",
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["docx", "pdf"]),
      notes: "Name options, taglines and rationale; record rights/restrictions.",
    }),
    beforeCreateChecks: brandingBefore,
    howToCreate: Object.freeze([
      "Record approval and rights for proposed names, taglines and fonts.",
      "Flag naming restrictions and trademark review needs.",
    ]),
    hygieneChecks: BRANDING_HYGIENE,
  }),
  rule({
    id: "branding.other.default",
    service: "branding",
    subtype: "other",
    placement: "default",
    status: "D",
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["pdf", "png", "svg"]),
      notes: "Clarify branding deliverable kind before production.",
    }),
    beforeCreateChecks: brandingBefore,
    howToCreate: brandingHowTo,
    hygieneChecks: BRANDING_HYGIENE,
  }),

  // —— Service 04 — Packaging ——
  rule({
    id: "packaging.boxes.default",
    service: "packaging",
    subtype: "boxes",
    placement: "default",
    status: "R",
    colour: "CMYK",
    export: packagingExport,
    productionNote: "Create from approved vendor dieline at 1:1 — no generic canvas.",
    beforeCreateChecks: packagingBefore,
    howToCreate: packagingHowTo,
    hygieneChecks: PACKAGING_HYGIENE,
  }),
  rule({
    id: "packaging.pouches.default",
    service: "packaging",
    subtype: "pouches",
    placement: "default",
    status: "R",
    colour: "CMYK",
    export: packagingExport,
    productionNote: "Vendor dieline required; seal and fold clearances apply.",
    beforeCreateChecks: packagingBefore,
    howToCreate: packagingHowTo,
    hygieneChecks: PACKAGING_HYGIENE,
  }),
  rule({
    id: "packaging.wrapper.default",
    service: "packaging",
    subtype: "wrapper",
    placement: "default",
    status: "R",
    colour: "CMYK",
    export: packagingExport,
    beforeCreateChecks: packagingBefore,
    howToCreate: packagingHowTo,
    hygieneChecks: PACKAGING_HYGIENE,
  }),
  rule({
    id: "packaging.bottles.default",
    service: "packaging",
    subtype: "bottles",
    placement: "default",
    status: "R",
    colour: "CMYK",
    export: packagingExport,
    productionNote: "Label/wrap panels from approved bottle dieline.",
    beforeCreateChecks: packagingBefore,
    howToCreate: packagingHowTo,
    hygieneChecks: PACKAGING_HYGIENE,
  }),
  rule({
    id: "packaging.jars.default",
    service: "packaging",
    subtype: "jars",
    placement: "default",
    status: "R",
    colour: "CMYK",
    export: packagingExport,
    beforeCreateChecks: packagingBefore,
    howToCreate: packagingHowTo,
    hygieneChecks: PACKAGING_HYGIENE,
  }),
  rule({
    id: "packaging.tubes.default",
    service: "packaging",
    subtype: "tubes",
    placement: "default",
    status: "R",
    colour: "CMYK",
    export: packagingExport,
    beforeCreateChecks: packagingBefore,
    howToCreate: packagingHowTo,
    hygieneChecks: PACKAGING_HYGIENE,
  }),
  rule({
    id: "packaging.labels.default",
    service: "packaging",
    subtype: "labels",
    placement: "default",
    status: "R",
    colour: "CMYK",
    export: packagingExport,
    productionNote: "Label size from vendor template; barcode quiet zone required.",
    beforeCreateChecks: packagingBefore,
    howToCreate: packagingHowTo,
    hygieneChecks: PACKAGING_HYGIENE,
  }),
  rule({
    id: "packaging.gift-packs.default",
    service: "packaging",
    subtype: "gift-packs",
    placement: "default",
    status: "R",
    colour: "CMYK",
    export: packagingExport,
    beforeCreateChecks: packagingBefore,
    howToCreate: packagingHowTo,
    hygieneChecks: PACKAGING_HYGIENE,
  }),
  rule({
    id: "packaging.other.default",
    service: "packaging",
    subtype: "other",
    placement: "default",
    status: "R",
    colour: "CMYK",
    export: packagingExport,
    productionNote: "Structural pack — confirm dieline before production.",
    beforeCreateChecks: packagingBefore,
    howToCreate: packagingHowTo,
    hygieneChecks: PACKAGING_HYGIENE,
  }),

  // —— Service 05 — Print & OOH ——
  rule({
    id: "print.brochures.default",
    service: "print",
    subtype: "brochures",
    placement: "default",
    status: "D",
    canvas: { width: 210, height: 297, unit: "mm" },
    colour: "agreed-print",
    export: Object.freeze({
      formats: Object.freeze(["pdf"]),
      notes: "A4 example: 210×297 mm trim; 3 mm bleed → 216×303 mm artwork extent.",
    }),
    print: { bleedMm: 3, effectivePpi: 300 },
    productionNote: "3 mm bleed is a house starting point; vendor rules override.",
    beforeCreateChecks: printBefore,
    howToCreate: printHowTo,
    hygieneChecks: PRINT_HYGIENE,
  }),
  rule({
    id: "print.leaflets.default",
    service: "print",
    subtype: "leaflets",
    placement: "default",
    status: "D",
    canvas: { width: 148, height: 210, unit: "mm" },
    colour: "agreed-print",
    export: Object.freeze({
      formats: Object.freeze(["pdf"]),
      notes: "A5 example: 148×210 mm; 3 mm bleed → 154×216 mm artwork extent.",
    }),
    print: { bleedMm: 3, effectivePpi: 300 },
    beforeCreateChecks: printBefore,
    howToCreate: Object.freeze([
      "Front/back print PDF + proof.",
      "3 mm bleed is only a house starting point for small print.",
    ]),
    hygieneChecks: PRINT_HYGIENE,
  }),
  rule({
    id: "print.posters.default",
    service: "print",
    subtype: "posters",
    placement: "default",
    status: "D",
    canvas: { width: 297, height: 420, unit: "mm" },
    colour: "agreed-print",
    export: Object.freeze({
      formats: Object.freeze(["pdf"]),
      notes: "A3 house example: 297×420 mm trim; apply agreed bleed.",
    }),
    print: { bleedMm: 3, effectivePpi: 300 },
    beforeCreateChecks: printBefore,
    howToCreate: printHowTo,
    hygieneChecks: PRINT_HYGIENE,
  }),
  rule({
    id: "print.print-ads.default",
    service: "print",
    subtype: "print-ads",
    placement: "default",
    status: "D",
    colour: "agreed-print",
    export: Object.freeze({
      formats: Object.freeze(["pdf"]),
      notes: "Publication trim size required; no universal magazine/newspaper canvas.",
    }),
    print: { bleedMm: 3, effectivePpi: 300 },
    productionNote: "Confirm booked publication mechanical before production.",
    beforeCreateChecks: printBefore,
    howToCreate: printHowTo,
    hygieneChecks: PRINT_HYGIENE,
  }),
  rule({
    id: "print.ooh-design.default",
    service: "print",
    subtype: "ooh-design",
    placement: "default",
    status: "R",
    colour: "vendor",
    export: Object.freeze({
      formats: Object.freeze(["pdf"]),
      notes: "Booked site ratio and dimensions; no universal billboard size.",
    }),
    productionNote: "Obtain booked site dimensions before production.",
    beforeCreateChecks: printBefore,
    howToCreate: Object.freeze([
      "Scaled artwork with scale clearly declared.",
      "OOH house message target: headline up to 8 words and one action.",
    ]),
    hygieneChecks: PRINT_HYGIENE,
  }),
  rule({
    id: "print.vehicle-design.default",
    service: "print",
    subtype: "vehicle-design",
    placement: "default",
    status: "R",
    colour: "vendor",
    export: Object.freeze({
      formats: Object.freeze(["pdf"]),
      notes: "Vehicle wrap panels from confirmed templates; no universal canvas.",
    }),
    productionNote: "Confirm vehicle templates and install tolerances before production.",
    beforeCreateChecks: printBefore,
    howToCreate: Object.freeze([
      "Compose on vendor vehicle templates; keep essential content clear of cuts and hardware.",
      "Vendor-approved print profile required.",
    ]),
    hygieneChecks: PRINT_HYGIENE,
  }),
  rule({
    id: "print.standees.default",
    service: "print",
    subtype: "standees",
    placement: "default",
    status: "D",
    canvas: { width: 850, height: 2000, unit: "mm" },
    colour: "vendor",
    export: Object.freeze({
      formats: Object.freeze(["pdf"]),
      notes: "850×2000 mm visible-area house example; vendor base take-up separate.",
    }),
    beforeCreateChecks: printBefore,
    howToCreate: Object.freeze([
      "Print artwork + standing-view proof.",
      "Vendor-approved print profile required.",
    ]),
    hygieneChecks: PRINT_HYGIENE,
  }),
  rule({
    id: "print.other.default",
    service: "print",
    subtype: "other",
    placement: "default",
    status: "R",
    colour: "vendor",
    export: Object.freeze({
      formats: Object.freeze(["pdf"]),
      notes: "Confirm physical size and vendor profile before production.",
    }),
    beforeCreateChecks: printBefore,
    howToCreate: printHowTo,
    hygieneChecks: PRINT_HYGIENE,
  }),

  // —— Service 06 — Video & Motion ——
  rule({
    id: "video.corporate-films.default",
    service: "video",
    subtype: "corporate-films",
    placement: "default",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "1920×1080 house example; duration follows brief.",
    beforeCreateChecks: videoBefore,
    howToCreate: videoHowTo,
    hygieneChecks: VIDEO_HYGIENE,
  }),
  rule({
    id: "video.explainer-videos.default",
    service: "video",
    subtype: "explainer-videos",
    placement: "default",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "Compose vertical (1080×1920) separately when briefed.",
    beforeCreateChecks: videoBefore,
    howToCreate: Object.freeze([
      ...videoHowTo,
      "Compose 16:9 and 9:16 separately rather than cropping one timeline blindly.",
    ]),
    hygieneChecks: VIDEO_HYGIENE,
  }),
  rule({
    id: "video.promo-videos.default",
    service: "video",
    subtype: "promo-videos",
    placement: "default",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "House short promo example 15 s; not a platform maximum.",
    beforeCreateChecks: videoBefore,
    howToCreate: Object.freeze([
      ...videoHowTo,
      "Compose vertical separately when the bought placement is 9:16.",
    ]),
    hygieneChecks: VIDEO_HYGIENE,
  }),
  rule({
    id: "video.motion-graphics.default",
    service: "video",
    subtype: "motion-graphics",
    placement: "default",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    beforeCreateChecks: videoBefore,
    howToCreate: videoHowTo,
    hygieneChecks: VIDEO_HYGIENE,
  }),
  rule({
    id: "video.2d-animation.default",
    service: "video",
    subtype: "2d-animation",
    placement: "default",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    beforeCreateChecks: videoBefore,
    howToCreate: videoHowTo,
    hygieneChecks: VIDEO_HYGIENE,
  }),
  rule({
    id: "video.3d-animation.default",
    service: "video",
    subtype: "3d-animation",
    placement: "default",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    beforeCreateChecks: videoBefore,
    howToCreate: videoHowTo,
    hygieneChecks: VIDEO_HYGIENE,
  }),
  rule({
    id: "video.vfx.default",
    service: "video",
    subtype: "vfx",
    placement: "default",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    beforeCreateChecks: videoBefore,
    howToCreate: videoHowTo,
    hygieneChecks: VIDEO_HYGIENE,
  }),
  rule({
    id: "video.video-editing.default",
    service: "video",
    subtype: "video-editing",
    placement: "default",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    beforeCreateChecks: videoBefore,
    howToCreate: videoHowTo,
    hygieneChecks: VIDEO_HYGIENE,
  }),
  rule({
    id: "video.storyboards.default",
    service: "video",
    subtype: "storyboards",
    placement: "default",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["png", "jpg", "pdf"]),
      notes: "Sequential storyboard frames; image/PDF acceptable house delivery.",
    }),
    productionNote: "Still frames with scene notes; match intended video aspect when known.",
    beforeCreateChecks: videoBefore,
    howToCreate: Object.freeze([
      "Number frames and include scene notes / VO cues.",
      "Keep one ratio throughout the board set.",
    ]),
    hygieneChecks: VIDEO_HYGIENE,
  }),
  rule({
    id: "video.other.default",
    service: "video",
    subtype: "other",
    placement: "default",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    beforeCreateChecks: videoBefore,
    howToCreate: videoHowTo,
    hygieneChecks: VIDEO_HYGIENE,
  }),

  // —— Service 07 — Presentations ——
  rule({
    id: "presentations.corporate.default",
    service: "presentations",
    subtype: "corporate",
    placement: "default",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "screen-rgb",
    export: presentationExport,
    productionNote: "16:9 house presentation canvas.",
    beforeCreateChecks: presentationBefore,
    howToCreate: presentationHowTo,
    hygieneChecks: PRESENTATION_HYGIENE,
  }),
  rule({
    id: "presentations.pitch-decks.default",
    service: "presentations",
    subtype: "pitch-decks",
    placement: "default",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "screen-rgb",
    export: Object.freeze({
      formats: Object.freeze(["pptx", "pdf"]),
      notes: "16:9 pitch structure.",
    }),
    beforeCreateChecks: presentationBefore,
    howToCreate: Object.freeze([
      "Problem → insight → solution → evidence → plan → ask.",
      "Every external number needs a source/date.",
    ]),
    hygieneChecks: PRESENTATION_HYGIENE,
  }),
  rule({
    id: "presentations.product.default",
    service: "presentations",
    subtype: "product",
    placement: "default",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "screen-rgb",
    export: presentationExport,
    beforeCreateChecks: presentationBefore,
    howToCreate: presentationHowTo,
    hygieneChecks: PRESENTATION_HYGIENE,
  }),
  rule({
    id: "presentations.training.default",
    service: "presentations",
    subtype: "training",
    placement: "default",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "screen-rgb",
    export: presentationExport,
    beforeCreateChecks: presentationBefore,
    howToCreate: presentationHowTo,
    hygieneChecks: PRESENTATION_HYGIENE,
  }),
  rule({
    id: "presentations.infographics.default",
    service: "presentations",
    subtype: "infographics",
    placement: "default",
    status: "D",
    canvas: { width: 1080, height: 1350, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Data-led still; use 1920×1080 when destined for slide decks.",
    beforeCreateChecks: presentationBefore,
    howToCreate: Object.freeze([
      "Source every external number with date; label examples clearly.",
      "Export readable without zooming for intended viewing context.",
    ]),
    hygieneChecks: PRESENTATION_HYGIENE,
  }),
  rule({
    id: "presentations.gifs.default",
    service: "presentations",
    subtype: "gifs",
    placement: "default",
    status: "D",
    canvas: { width: 1080, height: 1080, unit: "px" },
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["gif", "mp4", "png"]),
      notes: "Short looping visual; prefer MP4 when platform allows.",
    }),
    beforeCreateChecks: presentationBefore,
    howToCreate: Object.freeze([
      "Keep loops short and readable; no essential text below legibility.",
      "Test playback in the delivery environment.",
    ]),
    hygieneChecks: PRESENTATION_HYGIENE,
  }),
  rule({
    id: "presentations.templates.default",
    service: "presentations",
    subtype: "templates",
    placement: "default",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "screen-rgb",
    export: Object.freeze({
      formats: Object.freeze(["pptx"]),
      notes: "Editable 16:9 template system with masters.",
    }),
    beforeCreateChecks: presentationBefore,
    howToCreate: Object.freeze([
      "Keep charts and text editable; do not fake editability with flat images.",
      "Consistent margins and type hierarchy across masters.",
    ]),
    hygieneChecks: PRESENTATION_HYGIENE,
  }),
  rule({
    id: "presentations.other.default",
    service: "presentations",
    subtype: "other",
    placement: "default",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "screen-rgb",
    export: presentationExport,
    beforeCreateChecks: presentationBefore,
    howToCreate: presentationHowTo,
    hygieneChecks: PRESENTATION_HYGIENE,
  }),

  // —— Service 08 — Email Design ——
  rule({
    id: "email.emailers.default",
    service: "email",
    subtype: "emailers",
    placement: "default",
    status: "D",
    canvas: { width: 600, height: 800, unit: "px" },
    colour: "sRGB",
    export: emailExport,
    productionNote: "600 px content width house target.",
    beforeCreateChecks: emailBefore,
    howToCreate: emailHowTo,
    hygieneChecks: EMAIL_HYGIENE,
  }),
  rule({
    id: "email.newsletters.default",
    service: "email",
    subtype: "newsletters",
    placement: "default",
    status: "D",
    canvas: { width: 600, height: 1200, unit: "px" },
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["html", "png", "jpg"]),
      notes: "600 px modular layout; 3–5 editorial blocks house target.",
    }),
    beforeCreateChecks: emailBefore,
    howToCreate: Object.freeze([
      "Use one primary CTA and test the real link.",
      "Proof subject, preheader, personalization fallbacks, footer and unsubscribe where applicable.",
    ]),
    hygieneChecks: EMAIL_HYGIENE,
  }),
  rule({
    id: "email.other.default",
    service: "email",
    subtype: "other",
    placement: "default",
    status: "D",
    canvas: { width: 600, height: 800, unit: "px" },
    colour: "sRGB",
    export: emailExport,
    beforeCreateChecks: emailBefore,
    howToCreate: emailHowTo,
    hygieneChecks: EMAIL_HYGIENE,
  }),

  // —— Service 09 — POS / In-Store ——
  rule({
    id: "pos.product-display-units.default",
    service: "pos",
    subtype: "product-display-units",
    placement: "default",
    status: "R",
    colour: "vendor",
    export: Object.freeze({
      formats: Object.freeze(["pdf", "png"]),
      notes: "Fixture measurements required; environmental / 3D visualization primary.",
    }),
    productionNote: "No universal display-unit canvas — confirm fixture drawings.",
    beforeCreateChecks: posBefore,
    howToCreate: posHowTo,
    hygieneChecks: POS_HYGIENE,
  }),
  rule({
    id: "pos.branding-elements.default",
    service: "pos",
    subtype: "branding-elements",
    placement: "default",
    status: "R",
    colour: "vendor",
    export: Object.freeze({
      formats: Object.freeze(["pdf", "png"]),
      notes: "Shelf strips and in-store graphics from confirmed sizes.",
    }),
    beforeCreateChecks: posBefore,
    howToCreate: posHowTo,
    hygieneChecks: POS_HYGIENE,
  }),
  rule({
    id: "pos.sampling-booths.default",
    service: "pos",
    subtype: "sampling-booths",
    placement: "default",
    status: "R",
    canvas: { width: 1200, height: 900, unit: "px" },
    colour: "vendor",
    export: Object.freeze({
      formats: Object.freeze(["png", "pdf"]),
      notes: "1200×900 px house visualization example; physical build from vendor drawings.",
    }),
    productionNote: "Canvas example for concept viz only — not a production dieline.",
    beforeCreateChecks: posBefore,
    howToCreate: posHowTo,
    hygieneChecks: POS_HYGIENE,
  }),
  rule({
    id: "pos.store-branding.default",
    service: "pos",
    subtype: "store-branding",
    placement: "default",
    status: "R",
    colour: "vendor",
    export: Object.freeze({
      formats: Object.freeze(["pdf", "png"]),
      notes: "Storewide system from confirmed site plans.",
    }),
    beforeCreateChecks: posBefore,
    howToCreate: posHowTo,
    hygieneChecks: POS_HYGIENE,
  }),
  rule({
    id: "pos.other.default",
    service: "pos",
    subtype: "other",
    placement: "default",
    status: "R",
    colour: "vendor",
    export: Object.freeze({
      formats: Object.freeze(["pdf", "png"]),
      notes: "Confirm fixture/site dimensions before production.",
    }),
    beforeCreateChecks: posBefore,
    howToCreate: posHowTo,
    hygieneChecks: POS_HYGIENE,
  }),

  // —— Service 10 — Merchandise ——
  rule({
    id: "merchandise.t-shirts.default",
    service: "merchandise",
    subtype: "t-shirts",
    placement: "default",
    status: "R",
    colour: "vendor",
    export: Object.freeze({
      formats: Object.freeze(["png", "pdf", "svg"]),
      notes: "Chest print house note: ~100 mm wide; mockup is primary deliverable.",
    }),
    productionNote: "Chest print house starting point ~100 mm; confirm garment template.",
    beforeCreateChecks: merchBefore,
    howToCreate: Object.freeze([
      ...merchHowTo,
      "State chest print size (~100 mm house note) and garment side explicitly.",
    ]),
    hygieneChecks: MERCHANDISE_HYGIENE,
  }),
  rule({
    id: "merchandise.caps.default",
    service: "merchandise",
    subtype: "caps",
    placement: "default",
    status: "R",
    colour: "vendor",
    export: Object.freeze({
      formats: Object.freeze(["png", "pdf", "svg"]),
      notes: "Cap embroidery house note: ~60 mm wide; mockup primary.",
    }),
    productionNote: "Embroidery house starting point ~60 mm; confirm stitch method.",
    beforeCreateChecks: merchBefore,
    howToCreate: Object.freeze([
      ...merchHowTo,
      "Design for embroidery at ~60 mm house width unless vendor overrides.",
    ]),
    hygieneChecks: MERCHANDISE_HYGIENE,
  }),
  rule({
    id: "merchandise.jackets.default",
    service: "merchandise",
    subtype: "jackets",
    placement: "default",
    status: "R",
    colour: "vendor",
    export: Object.freeze({
      formats: Object.freeze(["png", "pdf", "svg"]),
      notes: "Jacket decoration from confirmed placement templates.",
    }),
    beforeCreateChecks: merchBefore,
    howToCreate: merchHowTo,
    hygieneChecks: MERCHANDISE_HYGIENE,
  }),
  rule({
    id: "merchandise.mugs.default",
    service: "merchandise",
    subtype: "mugs",
    placement: "default",
    status: "R",
    colour: "vendor",
    export: Object.freeze({
      formats: Object.freeze(["png", "pdf"]),
      notes: "Wrap/print area from vendor template; mockup primary.",
    }),
    beforeCreateChecks: merchBefore,
    howToCreate: merchHowTo,
    hygieneChecks: MERCHANDISE_HYGIENE,
  }),
  rule({
    id: "merchandise.bottles.default",
    service: "merchandise",
    subtype: "bottles",
    placement: "default",
    status: "R",
    colour: "vendor",
    export: Object.freeze({
      formats: Object.freeze(["png", "pdf"]),
      notes: "Bottle imprint area from vendor template.",
    }),
    beforeCreateChecks: merchBefore,
    howToCreate: merchHowTo,
    hygieneChecks: MERCHANDISE_HYGIENE,
  }),
  rule({
    id: "merchandise.pens-notepads.default",
    service: "merchandise",
    subtype: "pens-notepads",
    placement: "default",
    status: "R",
    colour: "vendor",
    export: Object.freeze({
      formats: Object.freeze(["png", "pdf"]),
      notes: "Stationery imprint areas from supplier templates.",
    }),
    beforeCreateChecks: merchBefore,
    howToCreate: merchHowTo,
    hygieneChecks: MERCHANDISE_HYGIENE,
  }),
  rule({
    id: "merchandise.bags.default",
    service: "merchandise",
    subtype: "bags",
    placement: "default",
    status: "R",
    colour: "vendor",
    export: Object.freeze({
      formats: Object.freeze(["png", "pdf", "svg"]),
      notes: "Bag print area from confirmed size and method.",
    }),
    beforeCreateChecks: merchBefore,
    howToCreate: merchHowTo,
    hygieneChecks: MERCHANDISE_HYGIENE,
  }),
  rule({
    id: "merchandise.keychains.default",
    service: "merchandise",
    subtype: "keychains",
    placement: "default",
    status: "R",
    colour: "vendor",
    export: Object.freeze({
      formats: Object.freeze(["png", "pdf", "svg"]),
      notes: "Keychain art for selected fabrication method.",
    }),
    beforeCreateChecks: merchBefore,
    howToCreate: merchHowTo,
    hygieneChecks: MERCHANDISE_HYGIENE,
  }),
  rule({
    id: "merchandise.trophy.default",
    service: "merchandise",
    subtype: "trophy",
    placement: "default",
    status: "R",
    colour: "vendor",
    export: Object.freeze({
      formats: Object.freeze(["png", "pdf"]),
      notes: "3D visualization primary; fabrication drawings from vendor.",
    }),
    beforeCreateChecks: merchBefore,
    howToCreate: merchHowTo,
    hygieneChecks: MERCHANDISE_HYGIENE,
  }),
  rule({
    id: "merchandise.gift-hampers.default",
    service: "merchandise",
    subtype: "gift-hampers",
    placement: "default",
    status: "R",
    colour: "vendor",
    export: Object.freeze({
      formats: Object.freeze(["png", "pdf"]),
      notes: "Hamper presentation mockup; contents and packing confirmed separately.",
    }),
    beforeCreateChecks: merchBefore,
    howToCreate: merchHowTo,
    hygieneChecks: MERCHANDISE_HYGIENE,
  }),
  rule({
    id: "merchandise.other.default",
    service: "merchandise",
    subtype: "other",
    placement: "default",
    status: "R",
    colour: "vendor",
    export: Object.freeze({
      formats: Object.freeze(["png", "pdf"]),
      notes: "Confirm decoration method and item template before production.",
    }),
    beforeCreateChecks: merchBefore,
    howToCreate: merchHowTo,
    hygieneChecks: MERCHANDISE_HYGIENE,
  }),

  // —— Service 11 — Illustration ——
  rule({
    id: "illustration.concept-art.default",
    service: "illustration",
    subtype: "concept-art",
    placement: "default",
    status: "D",
    canvas: { width: 3000, height: 3000, unit: "px" },
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["png", "jpg", "psd"]),
      notes: "3000 px longest-edge house capture/export target.",
    }),
    productionNote: "Longest edge ≥3000 px house target unless brief overrides.",
    beforeCreateChecks: illustrationBefore,
    howToCreate: illustrationHowTo,
    hygieneChecks: ILLUSTRATION_HYGIENE,
  }),
  rule({
    id: "illustration.mascot-design.default",
    service: "illustration",
    subtype: "mascot-design",
    placement: "default",
    status: "D",
    canvas: { width: 2400, height: 2400, unit: "px" },
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["png", "svg", "pdf"]),
      notes: "Character set with clear poses; vector preferred when scalable.",
    }),
    beforeCreateChecks: illustrationBefore,
    howToCreate: Object.freeze([
      ...illustrationHowTo,
      "Ensure the key shape still reads at final display size.",
    ]),
    hygieneChecks: ILLUSTRATION_HYGIENE,
  }),
  rule({
    id: "illustration.infographics.default",
    service: "illustration",
    subtype: "infographics",
    placement: "default",
    status: "D",
    canvas: { width: 1080, height: 1350, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "1080×1350 house infographic canvas.",
    beforeCreateChecks: illustrationBefore,
    howToCreate: Object.freeze([
      ...illustrationHowTo,
      "Ground charts in approved source — invent nothing.",
    ]),
    hygieneChecks: ILLUSTRATION_HYGIENE,
  }),
  rule({
    id: "illustration.technical.default",
    service: "illustration",
    subtype: "technical",
    placement: "default",
    status: "D",
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["png", "svg", "pdf"]),
      notes: "Technical diagram from approved source dimensions.",
    }),
    beforeCreateChecks: illustrationBefore,
    howToCreate: Object.freeze([
      ...illustrationHowTo,
      "Review technical objects against approved source before release.",
    ]),
    hygieneChecks: ILLUSTRATION_HYGIENE,
  }),
  rule({
    id: "illustration.other.default",
    service: "illustration",
    subtype: "other",
    placement: "default",
    status: "D",
    colour: "sRGB",
    export: srgbStill,
    beforeCreateChecks: illustrationBefore,
    howToCreate: illustrationHowTo,
    hygieneChecks: ILLUSTRATION_HYGIENE,
  }),

  // —— Service 12 — Visual Production / Photography ——
  rule({
    id: "photography.product.default",
    service: "photography",
    subtype: "product",
    placement: "default",
    status: "D",
    canvas: { width: 4000, height: 4000, unit: "px" },
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["jpg", "png", "tif"]),
      notes: "4000×4000 house product capture target; retain full subject in master.",
    }),
    productionNote: "House product capture target 4000 px.",
    beforeCreateChecks: photoBefore,
    howToCreate: photoHowTo,
    hygieneChecks: PHOTOGRAPHY_HYGIENE,
  }),
  rule({
    id: "photography.lifestyle.default",
    service: "photography",
    subtype: "lifestyle",
    placement: "default",
    status: "D",
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["jpg", "png"]),
      notes: "Lifestyle still; size follows briefed placement.",
    }),
    beforeCreateChecks: photoBefore,
    howToCreate: photoHowTo,
    hygieneChecks: PHOTOGRAPHY_HYGIENE,
  }),
  rule({
    id: "photography.corporate.default",
    service: "photography",
    subtype: "corporate",
    placement: "default",
    status: "D",
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["jpg", "png"]),
      notes: "Corporate portraits / workplace imagery; rights recorded.",
    }),
    beforeCreateChecks: photoBefore,
    howToCreate: photoHowTo,
    hygieneChecks: PHOTOGRAPHY_HYGIENE,
  }),
  rule({
    id: "photography.industrial.default",
    service: "photography",
    subtype: "industrial",
    placement: "default",
    status: "D",
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["jpg", "png"]),
      notes: "Industrial / facility imagery; disclose composites.",
    }),
    beforeCreateChecks: photoBefore,
    howToCreate: photoHowTo,
    hygieneChecks: PHOTOGRAPHY_HYGIENE,
  }),
  rule({
    id: "photography.event.default",
    service: "photography",
    subtype: "event",
    placement: "default",
    status: "D",
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["jpg", "png"]),
      notes: "Event coverage stills; model/property rights where applicable.",
    }),
    beforeCreateChecks: photoBefore,
    howToCreate: photoHowTo,
    hygieneChecks: PHOTOGRAPHY_HYGIENE,
  }),
  rule({
    id: "photography.retouching.default",
    service: "photography",
    subtype: "retouching",
    placement: "default",
    status: "D",
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["jpg", "png", "psd", "tif"]),
      notes: "Master + retouched derivatives named; no unapproved product alteration.",
    }),
    beforeCreateChecks: photoBefore,
    howToCreate: Object.freeze([
      ...photoHowTo,
      "Disclose generated or heavily composited treatments.",
    ]),
    hygieneChecks: PHOTOGRAPHY_HYGIENE,
  }),
  rule({
    id: "photography.other.default",
    service: "photography",
    subtype: "other",
    placement: "default",
    status: "D",
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["jpg", "png"]),
      notes: "Clarify shot type and delivery crops before production.",
    }),
    beforeCreateChecks: photoBefore,
    howToCreate: photoHowTo,
    hygieneChecks: PHOTOGRAPHY_HYGIENE,
  }),

  // —— Service 13 — Brand Strategy ——
  rule({
    id: "strategy.brand-strategy.default",
    service: "strategy",
    subtype: "brand-strategy",
    placement: "default",
    status: "D",
    colour: "sRGB",
    export: documentExport,
    productionNote: "Strategy document; placement-appropriate canvases when visual pages included.",
    beforeCreateChecks: strategyBefore,
    howToCreate: strategyHowTo,
    hygieneChecks: STRATEGY_HYGIENE,
  }),
  rule({
    id: "strategy.other.default",
    service: "strategy",
    subtype: "other",
    placement: "default",
    status: "D",
    colour: "sRGB",
    export: documentExport,
    beforeCreateChecks: strategyBefore,
    howToCreate: strategyHowTo,
    hygieneChecks: STRATEGY_HYGIENE,
  }),

  // —— Service 14 — Ad Campaigns ——
  rule({
    id: "ads.performance-ads.default",
    service: "ads",
    subtype: "performance-ads",
    placement: "default",
    status: "D",
    canvas: { width: 1080, height: 1080, unit: "px" },
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["png", "jpg", "mp4"]),
      notes: "Placement-appropriate; use platform cards when bought placement is known.",
    }),
    productionNote: "House still example 1080×1080 when placement unspecified — not a platform card.",
    beforeCreateChecks: adsBefore,
    howToCreate: adsHowTo,
    hygieneChecks: ADS_HYGIENE,
  }),
  rule({
    id: "ads.other.default",
    service: "ads",
    subtype: "other",
    placement: "default",
    status: "D",
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["png", "jpg", "mp4", "txt"]),
      notes: "Clarify ad format and bought placement before production.",
    }),
    beforeCreateChecks: adsBefore,
    howToCreate: adsHowTo,
    hygieneChecks: ADS_HYGIENE,
  }),

  // —— Service 15 — Event Branding ——
  rule({
    id: "event.event-concept.default",
    service: "event",
    subtype: "event-concept",
    placement: "default",
    status: "D",
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["pdf", "pptx", "png"]),
      notes: "Theme, direction and mood; venue dimensions confirmed separately.",
    }),
    beforeCreateChecks: eventBefore,
    howToCreate: eventHowTo,
    hygieneChecks: EVENT_HYGIENE,
  }),
  rule({
    id: "event.event-identity.default",
    service: "event",
    subtype: "event-identity",
    placement: "default",
    status: "D",
    canvas: { width: 2400, height: 2400, unit: "px" },
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["svg", "pdf", "png"]),
      notes: "Event logo/system assets; vector + raster exports.",
    }),
    beforeCreateChecks: eventBefore,
    howToCreate: Object.freeze([
      ...eventHowTo,
      "Keep one grid, type hierarchy and identifier scheme across touchpoints.",
    ]),
    hygieneChecks: EVENT_HYGIENE,
  }),
  rule({
    id: "event.content-design.default",
    service: "event",
    subtype: "content-design",
    placement: "default",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["png", "jpg", "pptx", "mp4"]),
      notes: "Invites, screens, signage or decks — use confirmed venue sizes when known.",
    }),
    productionNote: "House screen example 1920×1080; print/signage sizes are venue-confirmed.",
    beforeCreateChecks: eventBefore,
    howToCreate: eventHowTo,
    hygieneChecks: EVENT_HYGIENE,
  }),
  rule({
    id: "event.other.default",
    service: "event",
    subtype: "other",
    placement: "default",
    status: "D",
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["pdf", "png"]),
      notes: "Clarify event deliverable and venue constraints before production.",
    }),
    beforeCreateChecks: eventBefore,
    howToCreate: eventHowTo,
    hygieneChecks: EVENT_HYGIENE,
  }),
]);

/** service/subtype → rule id (includes legacy aliases). */
export const SERVICE_SUBTYPE_TO_RULE_ID: Readonly<Record<string, string>> =
  Object.freeze({
    // Social
    "social/strategy": "social.strategy.default",
    "social/content-design": "social.content-design.default",
    "social/copywriting": "social.copywriting.default",
    "social/carousel": "social.carousel.default",

    // Website (+ web/* aliases)
    "website/corporate-website": "website.corporate-website.default",
    "website/ecom-website": "website.ecom-website.default",
    "website/landing-page": "website.landing-page.default",
    "website/ui-design": "website.ui-design.default",
    "website/visual-asset": "website.visual-asset.default",
    "website/ux-strategy": "website.ux-strategy.default",
    "website/interactive-prototypes": "website.interactive-prototypes.default",
    "website/design-systems": "website.design-systems.default",
    "website/app-development": "website.app-development.default",
    "website/other": "website.other.default",
    "web/corporate-website": "website.corporate-website.default",
    "web/ecom-website": "website.ecom-website.default",
    "web/landing-page": "website.landing-page.default",
    "web/ui-design": "website.ui-design.default",
    "web/visual-asset": "website.visual-asset.default",
    "web/ux-strategy": "website.ux-strategy.default",
    "web/interactive-prototypes": "website.interactive-prototypes.default",
    "web/design-systems": "website.design-systems.default",
    "web/app-development": "website.app-development.default",
    "web/other": "website.other.default",

    // Branding
    "branding/logo-design": "branding.logo-design.default",
    "branding/visual-identity": "branding.visual-identity.default",
    "branding/brand-guidelines": "branding.brand-guidelines.default",
    "branding/brand-naming-taglines": "branding.brand-naming-taglines.default",
    "branding/other": "branding.other.default",

    // Packaging
    "packaging/boxes": "packaging.boxes.default",
    "packaging/boxes-cartons": "packaging.boxes.default",
    "packaging/pouches": "packaging.pouches.default",
    "packaging/wrapper": "packaging.wrapper.default",
    "packaging/bottles": "packaging.bottles.default",
    "packaging/jars": "packaging.jars.default",
    "packaging/tubes": "packaging.tubes.default",
    "packaging/labels": "packaging.labels.default",
    "packaging/gift-packs": "packaging.gift-packs.default",
    "packaging/other": "packaging.other.default",

    // Print
    "print/brochures": "print.brochures.default",
    "print/leaflets": "print.leaflets.default",
    "print/posters": "print.posters.default",
    "print/print-ads": "print.print-ads.default",
    "print/ooh-design": "print.ooh-design.default",
    "print/vehicle-design": "print.vehicle-design.default",
    "print/standees": "print.standees.default",
    "print/other": "print.other.default",

    // Video (+ legacy aliases)
    "video/corporate-films": "video.corporate-films.default",
    "video/explainer-videos": "video.explainer-videos.default",
    "video/explainer": "video.explainer-videos.default",
    "video/explainer-promo-videos": "video.explainer-videos.default",
    "video/promo-videos": "video.promo-videos.default",
    "video/promo": "video.promo-videos.default",
    "video/motion-graphics": "video.motion-graphics.default",
    "video/2d-animation": "video.2d-animation.default",
    "video/3d-animation": "video.3d-animation.default",
    "video/vfx": "video.vfx.default",
    "video/video-editing": "video.video-editing.default",
    "video/storyboards": "video.storyboards.default",
    "video/other": "video.other.default",

    // Presentations
    "presentations/corporate": "presentations.corporate.default",
    "presentations/pitch-decks": "presentations.pitch-decks.default",
    "presentations/pitch": "presentations.pitch-decks.default",
    "presentations/product": "presentations.product.default",
    "presentations/training": "presentations.training.default",
    "presentations/infographics": "presentations.infographics.default",
    "presentations/gifs": "presentations.gifs.default",
    "presentations/templates": "presentations.templates.default",
    "presentations/other": "presentations.other.default",

    // Email
    "email/emailers": "email.emailers.default",
    "email/newsletters": "email.newsletters.default",
    "email/other": "email.other.default",

    // POS
    "pos/product-display-units": "pos.product-display-units.default",
    "pos/branding-elements": "pos.branding-elements.default",
    "pos/sampling-booths": "pos.sampling-booths.default",
    "pos/store-branding": "pos.store-branding.default",
    "pos/other": "pos.other.default",

    // Merchandise
    "merchandise/t-shirts": "merchandise.t-shirts.default",
    "merchandise/caps": "merchandise.caps.default",
    "merchandise/jackets": "merchandise.jackets.default",
    "merchandise/mugs": "merchandise.mugs.default",
    "merchandise/bottles": "merchandise.bottles.default",
    "merchandise/pens-notepads": "merchandise.pens-notepads.default",
    "merchandise/bags": "merchandise.bags.default",
    "merchandise/keychains": "merchandise.keychains.default",
    "merchandise/trophy": "merchandise.trophy.default",
    "merchandise/gift-hampers": "merchandise.gift-hampers.default",
    "merchandise/other": "merchandise.other.default",

    // Illustration
    "illustration/concept-art": "illustration.concept-art.default",
    "illustration/mascot-design": "illustration.mascot-design.default",
    "illustration/infographics": "illustration.infographics.default",
    "illustration/technical": "illustration.technical.default",
    "illustration/other": "illustration.other.default",

    // Photography (+ visual-production aliases)
    "photography/product": "photography.product.default",
    "photography/lifestyle": "photography.lifestyle.default",
    "photography/corporate": "photography.corporate.default",
    "photography/industrial": "photography.industrial.default",
    "photography/event": "photography.event.default",
    "photography/retouching": "photography.retouching.default",
    "photography/other": "photography.other.default",
    "visual-production/product": "photography.product.default",
    "visual-production/lifestyle": "photography.lifestyle.default",
    "visual-production/corporate": "photography.corporate.default",
    "visual-production/industrial": "photography.industrial.default",
    "visual-production/event": "photography.event.default",
    "visual-production/retouching": "photography.retouching.default",
    "visual-production/other": "photography.other.default",

    // Strategy
    "strategy/brand-strategy": "strategy.brand-strategy.default",
    "strategy/other": "strategy.other.default",
    "strategy/*": "strategy.brand-strategy.default",

    // Ads
    "ads/performance-ads": "ads.performance-ads.default",
    "ads/other": "ads.other.default",

    // Event
    "event/event-concept": "event.event-concept.default",
    "event/event-identity": "event.event-identity.default",
    "event/content-design": "event.content-design.default",
    "event/other": "event.other.default",
  });
