/** Snapchat field card — Format Spec p. 26. */

import { rule, srgbStill, videoWeb } from "./helpers";
import type { ProductionRule } from "../types";

export const SNAPCHAT_RULES: readonly ProductionRule[] = Object.freeze([
  rule({
    id: "snapchat.story-snap",
    platform: "snapchat",
    subtype: "content-design",
    placement: "story-snap",
    status: "D",
    canvas: { width: 1080, height: 1920, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "House production canvas; organic preview required.",
  }),
  rule({
    id: "snapchat.spotlight",
    platform: "snapchat",
    subtype: "content-design",
    placement: "spotlight",
    status: "D",
    canvas: { width: 1080, height: 1920, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "House production canvas; organic preview required.",
  }),
  rule({
    id: "snapchat.ad.single",
    platform: "snapchat",
    subtype: "content-design",
    placement: "ad.single",
    status: "V",
    sourceRef: "[S6]",
    canvas: { width: 720, height: 1280, unit: "px" },
    colour: "Rec.709",
    export: Object.freeze({
      formats: Object.freeze(["mp4", "mov", "png", "jpg"]),
      notes: "Current published 9:16 specification.",
    }),
    productionNote:
      "Verified primary ad canvas 720×1280 — house organic master remains 1080×1920.",
  }),
  rule({
    id: "snapchat.ad.collection",
    platform: "snapchat",
    subtype: "content-design",
    placement: "ad.collection",
    status: "V",
    sourceRef: "[S6]",
    canvas: { width: 720, height: 1280, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "9:16; do not use square product-card size as main canvas.",
  }),
  rule({
    id: "snapchat.ad.commercial",
    platform: "snapchat",
    subtype: "content-design",
    placement: "ad.commercial",
    status: "V",
    sourceRef: "[S6]",
    canvas: { width: 720, height: 1280, unit: "px" },
    colour: "Rec.709",
    export: Object.freeze({
      formats: Object.freeze(["mp4", "mov"]),
      notes: "9:16, H.264 MP4/MOV; standard 3–6 s, extended 7–180 s.",
    }),
    productionNote: "Verified commercial ad canvas.",
  }),
  rule({
    id: "snapchat.dynamic-product",
    platform: "snapchat",
    subtype: "content-design",
    placement: "dynamic-product",
    status: "R",
    canvas: { width: 1080, height: 1080, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Product source image only; confirm dynamic ad template.",
  }),
  rule({
    id: "snapchat.public-profile-cover",
    platform: "snapchat",
    subtype: "content-design",
    placement: "public-profile-cover",
    status: "R",
    canvas: { width: 1500, height: 500, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Supplied working preset; verify upload requirements.",
  }),
  rule({
    id: "snapchat.public-profile-logo",
    platform: "snapchat",
    subtype: "content-design",
    placement: "public-profile-logo",
    status: "R",
    canvas: { width: 320, height: 320, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Provisional icon master; crop test.",
  }),
  rule({
    id: "snapchat.lens-icon",
    platform: "snapchat",
    subtype: "content-design",
    placement: "lens-icon",
    status: "H",
    canvas: { width: 320, height: 320, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Do not confuse Lens icon and thumbnail; obtain current tool templates.",
  }),
  rule({
    id: "snapchat.brand-takeover",
    platform: "snapchat",
    subtype: "content-design",
    placement: "brand-takeover",
    status: "R",
    canvas: { width: 1080, height: 1920, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "Provisional C29 mapping; obtain booked-product spec before release.",
  }),
]);
