/** TikTok field card — Format Spec p. 25. */

import { rule, srgbStill, videoWeb } from "./helpers";
import type { ProductionRule } from "../types";

export const TIKTOK_RULES: readonly ProductionRule[] = Object.freeze([
  rule({
    id: "tiktok.feed",
    platform: "tiktok",
    subtype: "content-design",
    placement: "feed",
    status: "D",
    canvas: { width: 1080, height: 1920, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "Vertical working master; verify posting availability in target market.",
  }),
  rule({
    id: "tiktok.feed-image",
    platform: "tiktok",
    subtype: "content-design",
    placement: "feed-image",
    status: "D",
    canvas: { width: 1080, height: 1920, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Vertical working master for image/photo posts.",
  }),
  rule({
    id: "tiktok.photo-carousel",
    platform: "tiktok",
    subtype: "content-design",
    placement: "photo-carousel",
    status: "D",
    canvas: { width: 1080, height: 1920, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Vertical working master; verify posting availability.",
  }),
  rule({
    id: "tiktok.profile-picture",
    platform: "tiktok",
    subtype: "content-design",
    placement: "profile-picture",
    status: "D",
    canvas: { width: 200, height: 200, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Organic working preset, not paid profile spec.",
  }),
  rule({
    id: "tiktok.story",
    platform: "tiktok",
    subtype: "content-design",
    placement: "story",
    status: "R",
    canvas: { width: 1080, height: 1920, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "Confirm account/surface eligibility.",
  }),
  rule({
    id: "tiktok.live-cover",
    platform: "tiktok",
    subtype: "content-design",
    placement: "live-cover",
    status: "R",
    canvas: { width: 1080, height: 1920, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Confirm account/surface eligibility.",
  }),
  rule({
    id: "tiktok.reservation.in-feed",
    platform: "tiktok",
    subtype: "content-design",
    placement: "reservation.in-feed",
    status: "D",
    sourceRef: "[S5]",
    canvas: { width: 1080, height: 1920, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "9:16 house master; official minimum 540×960.",
  }),
  rule({
    id: "tiktok.spark-ads",
    platform: "tiktok",
    subtype: "content-design",
    placement: "spark-ads",
    status: "V",
    sourceRef: "[S5]",
    canvas: { width: 1080, height: 1920, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "Spark Ads Pull — use successfully published source post.",
  }),
  rule({
    id: "tiktok.paid-profile",
    platform: "tiktok",
    subtype: "content-design",
    placement: "paid-profile",
    status: "V",
    sourceRef: "[S5]",
    canvas: { width: 98, height: 98, unit: "px" },
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["jpg", "png"]),
      notes: "JPG/PNG <50 KB; protect central 66×66.",
    }),
    productionNote: "Paid profile image — protect central 66×66.",
  }),
  rule({
    id: "tiktok.profile-cover",
    platform: "tiktok",
    subtype: "content-design",
    placement: "profile-cover",
    status: "H",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Unverified supplied feature/size; do not approve automatically.",
  }),
  rule({
    id: "tiktok.topview",
    platform: "tiktok",
    subtype: "content-design",
    placement: "topview",
    status: "R",
    canvas: { width: 1080, height: 1920, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "Provisional master only; booked-product spec required.",
  }),
  rule({
    id: "tiktok.branded-effect-thumbnail",
    platform: "tiktok",
    subtype: "content-design",
    placement: "branded-effect-thumbnail",
    status: "H",
    canvas: { width: 1080, height: 1920, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Not verified; obtain current effect template.",
  }),
]);
