/** X (Twitter) field card — Format Spec p. 23. */

import { rule, srgbStill, videoWeb } from "./helpers";
import type { ProductionRule } from "../types";

export const X_RULES: readonly ProductionRule[] = Object.freeze([
  rule({
    id: "x.single-image.landscape",
    platform: "x",
    subtype: "content-design",
    placement: "single-image.landscape",
    status: "D",
    canvas: { width: 1600, height: 900, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Poll graphic supports, not replaces, a native poll.",
  }),
  rule({
    id: "x.square",
    platform: "x",
    subtype: "content-design",
    placement: "square",
    status: "D",
    canvas: { width: 1080, height: 1080, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Test multi-image preview crops.",
  }),
  rule({
    id: "x.portrait",
    platform: "x",
    subtype: "content-design",
    placement: "portrait",
    status: "D",
    canvas: { width: 1080, height: 1350, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Check timeline crop.",
  }),
  rule({
    id: "x.header",
    platform: "x",
    subtype: "content-design",
    placement: "header",
    status: "D",
    canvas: { width: 1500, height: 500, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Keep avatar and edge crops clear.",
  }),
  rule({
    id: "x.community-header",
    platform: "x",
    subtype: "content-design",
    placement: "community-header",
    status: "D",
    canvas: { width: 1500, height: 500, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Keep avatar and edge crops clear.",
  }),
  rule({
    id: "x.video.landscape",
    platform: "x",
    subtype: "content-design",
    placement: "video.landscape",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "Match actual posting context.",
  }),
  rule({
    id: "x.video.portrait",
    platform: "x",
    subtype: "content-design",
    placement: "video.portrait",
    status: "D",
    canvas: { width: 1080, height: 1920, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "Match actual posting context.",
  }),
  rule({
    id: "x.gif",
    platform: "x",
    subtype: "content-design",
    placement: "gif",
    status: "D",
    canvas: { width: 1080, height: 1080, unit: "px" },
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["gif", "png", "jpg"]),
      notes: "First frame must work independently.",
    }),
    productionNote: "First frame must work independently.",
  }),
  rule({
    id: "x.ad.website-click",
    platform: "x",
    subtype: "content-design",
    placement: "ad.website-click",
    status: "D",
    canvas: { width: 1200, height: 675, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Working creative canvas; confirm selected ad format.",
  }),
  rule({
    id: "x.link-preview",
    platform: "x",
    subtype: "content-design",
    placement: "link-preview",
    status: "D",
    canvas: { width: 1200, height: 628, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Check metadata and destination rendering.",
  }),
  rule({
    id: "x.ad.app-install",
    platform: "x",
    subtype: "content-design",
    placement: "ad.app-install",
    status: "V",
    sourceRef: "[S4]",
    canvas: { width: 800, height: 418, unit: "px" },
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["png", "jpg"]),
      notes: "PNG/JPEG up to 5 MB.",
    }),
    productionNote: "Recommended landscape app-button image; verified for cited ad product.",
  }),
  rule({
    id: "x.poll-graphic",
    platform: "x",
    subtype: "content-design",
    placement: "poll-graphic",
    status: "D",
    canvas: { width: 1600, height: 900, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Poll graphic supports, not replaces, a native poll.",
  }),
  rule({
    id: "x.quote-post",
    platform: "x",
    subtype: "content-design",
    placement: "quote-post",
    status: "D",
    canvas: { width: 1080, height: 1080, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Test multi-image preview crops.",
  }),
]);
