/** YouTube field card — Format Spec p. 24. */

import { rule, srgbStill, videoWeb } from "./helpers";
import type { ProductionRule } from "../types";

export const YOUTUBE_RULES: readonly ProductionRule[] = Object.freeze([
  rule({
    id: "youtube.channel-banner",
    platform: "youtube",
    subtype: "content-design",
    placement: "channel-banner",
    status: "V",
    sourceRef: "[S1]",
    canvas: { width: 2560, height: 1440, unit: "px" },
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["jpg", "png"]),
      notes: "Full canvas; 6 MB maximum. Not 1546×423.",
    }),
    productionNote: "Full 2560×1440 composition. Safe area is not the upload canvas.",
  }),
  rule({
    id: "youtube.banner-safe-area",
    platform: "youtube",
    subtype: "content-design",
    placement: "banner-safe-area",
    status: "V",
    sourceRef: "[S1]",
    canvas: { width: 1235, height: 338, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote:
      "Official safe area at minimum canvas 2048×1152; scale with chosen banner canvas.",
  }),
  rule({
    id: "youtube.video-thumbnail",
    platform: "youtube",
    subtype: "content-design",
    placement: "video-thumbnail",
    status: "V",
    sourceRef: "[S2]",
    canvas: { width: 3840, height: 2160, unit: "px" },
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["jpg", "png"]),
      notes: "Current recommendation retrieved; JPG/PNG.",
    }),
    productionNote: "Verified thumbnail recommendation — confirm publishing workflow.",
  }),
  rule({
    id: "youtube.shorts-thumbnail",
    platform: "youtube",
    subtype: "content-design",
    placement: "shorts-thumbnail",
    status: "V",
    sourceRef: "[S2]",
    canvas: { width: 2160, height: 3840, unit: "px" },
    colour: "sRGB",
    export: Object.freeze({
      formats: Object.freeze(["jpg", "png"]),
      notes: "Current recommended 9:16 canvas.",
    }),
    productionNote: "Verified Shorts thumbnail canvas — check publishing workflow.",
  }),
  rule({
    id: "youtube.channel-profile",
    platform: "youtube",
    subtype: "content-design",
    placement: "channel-profile",
    status: "D",
    canvas: { width: 800, height: 800, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "House master; official displayed image is 98×98.",
  }),
  rule({
    id: "youtube.community.square",
    platform: "youtube",
    subtype: "content-design",
    placement: "community.square",
    status: "D",
    canvas: { width: 1080, height: 1080, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Working preset; inspect published surface.",
  }),
  rule({
    id: "youtube.community.portrait",
    platform: "youtube",
    subtype: "content-design",
    placement: "community.portrait",
    status: "D",
    canvas: { width: 1080, height: 1350, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Working preset; inspect published surface.",
  }),
  rule({
    id: "youtube.community.landscape",
    platform: "youtube",
    subtype: "content-design",
    placement: "community.landscape",
    status: "D",
    canvas: { width: 1280, height: 720, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Working preset; inspect published surface.",
  }),
  rule({
    id: "youtube.video-end-screen",
    platform: "youtube",
    subtype: "content-design",
    placement: "video-end-screen",
    status: "D",
    canvas: { width: 1920, height: 1080, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "Native end-screen elements configured separately.",
  }),
  rule({
    id: "youtube.shorts-video",
    platform: "youtube",
    subtype: "content-design",
    placement: "shorts-video",
    status: "D",
    canvas: { width: 1080, height: 1920, unit: "px" },
    colour: "Rec.709",
    export: videoWeb,
    productionNote: "House 15 s promo example, not platform duration limit.",
  }),
  rule({
    id: "youtube.podcast-cover",
    platform: "youtube",
    subtype: "content-design",
    placement: "podcast-cover",
    status: "D",
    canvas: { width: 3000, height: 3000, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Square house master; keep central identity clear.",
  }),
  rule({
    id: "youtube.playlist-cover",
    platform: "youtube",
    subtype: "content-design",
    placement: "playlist-cover",
    status: "R",
    canvas: { width: 1080, height: 1080, unit: "px" },
    colour: "sRGB",
    export: srgbStill,
    productionNote: "Confirm playlist type and custom-cover support.",
  }),
]);
