apiVersion: v1
kind: ConfigMap
metadata:
  name: unagency-config
  namespace: unagency
data:
  NODE_ENV: "production"
  PORT: "3000"
  PERSISTENCE_DIALECT: "postgres"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  OBSERVABILITY_ENABLED: "true"
  LOG_LEVEL: "info"
