/**
 * End-to-end validation scenario definitions — stage graphs only.
 */

import type { ValidationScenarioDefinition } from "../contracts";

export const E2E_VALIDATION_SCENARIOS: readonly ValidationScenarioDefinition[] = [
  {
    scenarioId: "campaign_generation",
    name: "Campaign Generation",
    description:
      "Organization → Workspace → Brand → Campaign → Task/Capability → Brand Brain → Knowledge → Planning → Model/Provider → Generation → Evaluation → Storage → Gateway",
    stages: [
      "organization",
      "workspace",
      "brand",
      "campaign_request",
      "task_intelligence",
      "capability_intelligence",
      "brand_brain",
      "knowledge_intelligence",
      "planning",
      "model_selection",
      "provider_selection",
      "generation",
      "evaluation",
      "storage",
      "gateway_response",
    ],
    tags: ["marketing", "e2e", "brand-brain", "knowledge"],
  },
  {
    scenarioId: "website_generation",
    name: "Website Generation",
    description: "Page generation, SEO, brand adaptation, execution intelligence, audit, storage",
    stages: [
      "organization",
      "workspace",
      "brand_brain",
      "page_generation",
      "seo",
      "brand_adaptation",
      "generation",
      "execution_intelligence",
      "audit_trail",
      "storage",
      "gateway_response",
    ],
    tags: ["website", "seo"],
  },
  {
    scenarioId: "landing_page",
    name: "Landing Page",
    description: "Brand/knowledge retrieval, AI execution, explainability, quality evaluation",
    stages: [
      "brand_retrieval",
      "knowledge_retrieval",
      "ai_execution",
      "explainability",
      "quality_evaluation",
      "audit_trail",
      "gateway_response",
    ],
    tags: ["landing", "explainability"],
  },
  {
    scenarioId: "logo_generation",
    name: "Logo Generation",
    description: "Image provider routing, evaluation, storage, metadata, cost tracking",
    stages: [
      "image_routing",
      "provider_selection",
      "generation",
      "evaluation",
      "metadata",
      "cost_tracking",
      "storage",
      "gateway_response",
    ],
    tags: ["image", "logo"],
  },
  {
    scenarioId: "research_merge",
    name: "Research Provider Merge",
    description: "Validate Perplexity, Exa, Tavily merge paths",
    stages: [
      "research_providers",
      "capability_intelligence",
      "provider_selection",
      "generation",
      "evaluation",
      "gateway_response",
    ],
    tags: ["research", "perplexity", "exa", "tavily"],
  },
  {
    scenarioId: "gateway_e2e",
    name: "Gateway End-to-End",
    description: "API request through Gateway to execution intelligence explainability",
    stages: [
      "organization",
      "gateway_response",
      "ai_execution",
      "explainability",
      "audit_trail",
    ],
    tags: ["gateway", "api"],
  },
  {
    scenarioId: "task_graph_execution",
    name: "Task Graph Execution (Phase 5)",
    description:
      "OsExecutionPlan → TaskGraphExecutor → DAG dependency enforcement, parallel leaves, recovery, cancellation",
    stages: [
      "planning",
      "execution_intelligence",
      "task_graph_dag",
      "task_graph_parallelism",
      "task_graph_recovery",
      "task_graph_cancellation",
      "audit_trail",
      "storage",
    ],
    tags: ["phase5", "orchestration", "e2e"],
  },
  {
    scenarioId: "evaluation_governance",
    name: "Evaluation & Governance (Phase 6)",
    description:
      "Task outputs → SpecGuard/BrandGuard/Quality → Governance → Continue/Retry/Block/Human Review/Approve; execution-level approval distinct from technical success",
    stages: [
      "planning",
      "execution_intelligence",
      "generation",
      "evaluation",
      "spec_guard",
      "brand_guard",
      "quality_evaluation",
      "governance_decision",
      "human_review",
      "execution_approval",
      "tenant_isolation",
      "audit_trail",
    ],
    tags: ["phase6", "governance", "evaluation", "e2e"],
  },
  {
    scenarioId: "refinement_delivery",
    name: "Structured Refinement & Delivery (Phase 7)",
    description:
      "Approved output → max 5 adaptive MCQs → RefinementSpecification → replan/TaskGraph v2 → re-evaluate/re-approve → artifact version → approval-gated delivery",
    stages: [
      "structured_feedback",
      "adaptive_mcq",
      "refinement_specification",
      "refinement_execution",
      "evaluation",
      "governance_decision",
      "execution_approval",
      "artifact_versioning",
      "delivery_authorization",
      "delivery_idempotency",
      "tenant_isolation",
      "audit_trail",
    ],
    tags: ["phase7", "refinement", "delivery", "e2e"],
  },
  {
    scenarioId: "phase8_production_runtime",
    name: "Production Runtime & Durable Control Plane (Phase 8)",
    description:
      "Durable task-graph/evaluation/review/refinement/artifact/delivery state; per-task queue workers; multi-worker claim safety; restart recovery; Gateway OS APIs",
    stages: [
      "durable_execution",
      "queue_idempotency",
      "worker_recovery",
      "async_execution",
      "evaluation",
      "governance_decision",
      "human_review",
      "structured_feedback",
      "artifact_versioning",
      "delivery_authorization",
      "delivery_idempotency",
      "multi_worker_safety",
      "gateway_authorization",
      "tenant_isolation",
      "audit_trail",
    ],
    tags: ["phase8", "runtime", "queue", "gateway", "e2e"],
  },
  {
    scenarioId: "phase9_client_experience",
    name: "OS Client Experience & Human Interaction (Phase 9)",
    description:
      "Authenticated client → Gateway OS APIs only: execution lifecycle, real task progress, structured refinement ≤5, human review, artifact access, delivery, tenant isolation",
    stages: [
      "client_authentication",
      "client_execution_lifecycle",
      "task_graph_dag",
      "structured_feedback",
      "adaptive_mcq",
      "human_review",
      "artifact_versioning",
      "delivery_authorization",
      "gateway_authorization",
      "tenant_isolation",
    ],
    tags: ["phase9", "client", "gateway", "e2e"],
  },
];

export function getValidationScenario(
  id: ValidationScenarioDefinition["scenarioId"]
): ValidationScenarioDefinition | undefined {
  return E2E_VALIDATION_SCENARIOS.find((s) => s.scenarioId === id);
}
