/**
 * CDF service configs — spine from UNAGENCY CDF Developer Flow PDF.
 */

import type { CdfFlowPhase, CdfServiceConfig } from "./types";

function phase(
  partial: Omit<CdfFlowPhase, "generator"> & { generator?: CdfFlowPhase["generator"] },
): CdfFlowPhase {
  const generator =
    partial.generator ??
    (partial.type === "routes"
      ? // Config route cards are a user choice gate — do not auto-fan-out.
        // Services that need AI-generated routes set generator: "launch_routes" explicitly.
        partial.routes?.length
          ? "none"
          : "launch_routes"
      : partial.type === "text-approval"
        ? "text"
        : partial.type === "final"
          ? "materialize"
          : partial.type === "output" ||
              partial.type === "mockup" ||
              partial.type === "multi-output"
            ? "image"
            : "none");
  return { ...partial, generator };
}

export const socialMediaConfig: CdfServiceConfig = {
  serviceId: "social-media",
  service: "Social Media",
  outputMapService: "social",
  briefPlaceholder:
    "e.g. Create a post for our new mango drink. The idea is everyday energy.",
  briefAck:
    "Got it — I've read your brief. First, pick the platform this creative will run on.",
  studioHandoffAfterPhaseId: "output",
  phases: [
    phase({
      id: "platform",
      progressLabel: "Platform",
      entryMessage: "Where will this creative run?",
      type: "routes",
      generator: "none",
      choiceNoun: "Platform",
      selectionStayInChat: true,
      routes: [
        {
          label: "Instagram",
          title: "Instagram",
          desc: "Feed, Stories, Reels and related Instagram formats.",
        },
        {
          label: "Facebook",
          title: "Facebook",
          desc: "Feed, Stories and Facebook placement formats.",
        },
        {
          label: "LinkedIn",
          title: "LinkedIn",
          desc: "Professional feed and LinkedIn creative sizes.",
        },
        {
          label: "X",
          title: "X",
          desc: "X / Twitter post and media formats.",
        },
        {
          label: "Other",
          title: "Other",
          desc: "Another platform or a custom placement.",
        },
      ],
      postApproveMessage: "Platform locked. Set size or share a reference before directions.",
    }),
    phase({
      id: "size-reference",
      progressLabel: "Size / Reference",
      entryMessage: "Set the format size, or share a reference:",
      type: "routes",
      generator: "none",
      inherits: ["platform"],
      choiceNoun: "Size Option",
      selectionStayInChat: true,
      routes: [
        {
          label: "Enter Size",
          title: "Enter Size",
          desc: "Specify exact dimensions for this creative.",
        },
        {
          label: "Use Platform Size",
          title: "Use Platform Size",
          desc: "Use the recommended size for the selected platform.",
        },
        {
          label: "Upload Reference",
          title: "Upload Reference",
          desc: "Share inspiration or an existing creative to match.",
        },
        {
          label: "Skip",
          title: "Skip",
          desc: "Continue without a custom size or reference.",
        },
      ],
      postApproveMessage: "Format locked. Here are 3 creative directions:",
    }),
    phase({
      id: "routes",
      progressLabel: "Creative Directions",
      entryMessage: "Here are 3 creative directions for your social content:",
      type: "routes",
      generator: "launch_routes",
      inherits: ["size-reference"],
      choiceNoun: "Direction",
      selectionStayInChat: true,
      textLines: [
        "Direction name + one-line creative idea",
        "Visual treatment / composition thought",
        "Headline / message angle",
        "Why it fits this brief",
      ],
      postApproveMessage:
        "Perfect. Developing the selected direction now — generating your creative.",
    }),
    phase({
      id: "output",
      progressLabel: "Creative",
      entryMessage: "Here is your social creative based on the selected route:",
      type: "output",
      generator: "image",
      inherits: ["routes"],
      outputLabel: "Social Media Creative",
      refineExamples: [
        "Make the product bigger",
        "Remove the person",
        "Give me another headline",
        "Make the background lighter",
      ],
      approveLabel: "Approve Creative",
      postApproveMessage:
        "Creative approved. Would you like platform adaptations?",
    }),
    phase({
      id: "final",
      progressLabel: "Final",
      entryMessage:
        "Your social creative is ready. Export or request platform adaptations below.",
      type: "final",
      generator: "materialize",
      inherits: ["output"],
      finalActions: ["Download", "Create Another Size", "Request Adaptation"],
    }),
  ],
};

export const presentationConfig: CdfServiceConfig = {
  serviceId: "presentation",
  service: "Presentation",
  outputMapService: "presentations",
  briefPlaceholder:
    "Paste your brief, content or strategy document here — or describe what the presentation needs to communicate.",
  briefAck:
    "I've analysed your content. How would you like to provide the starting material?",
  studioHandoffAfterPhaseId: "full-deck",
  phases: [
    phase({
      id: "source",
      progressLabel: "Source Material",
      entryMessage: "How should we start the presentation?",
      type: "routes",
      generator: "none",
      choiceNoun: "Source",
      selectionStayInChat: true,
      routes: [
        {
          label: "Upload PPT",
          title: "Upload PPT",
          desc: "Upload an existing presentation to rebuild or refine.",
        },
        {
          label: "Paste Content",
          title: "Paste Content",
          desc: "Paste outline, notes or strategy content into chat.",
        },
        {
          label: "Start from Scratch",
          title: "Start from Scratch",
          desc: "Build the storyline from your brief alone.",
        },
      ],
      postApproveMessage: "Source path locked. Building the presentation storyline first.",
    }),
    phase({
      id: "storyline",
      progressLabel: "Storyline",
      entryMessage: "Here is the recommended presentation storyline:",
      type: "text-approval",
      generator: "structured",
      inherits: ["source"],
      textLines: [
        "Slide 1 — Opening / Context",
        "Slide 2 — The Challenge",
        "Slide 3 — The Opportunity",
        "Slide 4 — The Insight",
        "Slide 5 — Our Solution",
        "Slide 6 — How It Works",
        "Slide 7 — Why It Wins",
        "Slide 8 — Next Steps",
      ],
      refineExamples: [
        "Move Opportunity before Challenge",
        "Add one slide on competition",
        "Merge slides 6 and 7",
      ],
      approveLabel: "Approve Storyline",
      postApproveMessage:
        "Storyline approved. Generating slide-by-slide content now.",
    }),
    phase({
      id: "slide-content",
      progressLabel: "Slide Content",
      entryMessage: "Here is the full slide content across all 8 slides:",
      type: "text-approval",
      generator: "structured",
      inherits: ["storyline"],
      textLines: [
        "Slide 1 — Opening",
        "Slide 2 — The Challenge",
        "Slide 3 — The Opportunity",
        "Slide 4 — The Insight",
        "Slide 5 — The Solution",
        "Slide 6 — How It Works",
        "Slide 7 — Why It Wins",
        "Slide 8 — Next Steps",
      ],
      refineExamples: [
        "Reduce copy on slide 3",
        "Make the insight on slide 4 sharper",
      ],
      approveLabel: "Approve Slide Content",
      postApproveMessage: "Content approved. Here are 3 visual design routes:",
    }),
    phase({
      id: "design-routes",
      progressLabel: "Design Routes",
      entryMessage: "Here are 3 visual design directions for the presentation:",
      type: "routes",
      generator: "none",
      inherits: ["slide-content"],
      choiceNoun: "Design Route",
      selectionStayInChat: true,
      routes: [
        {
          label: "Route 1",
          title: "Clean Minimal",
          desc: "White space, refined typography, data-forward layouts.",
        },
        {
          label: "Route 2",
          title: "Bold Executive",
          desc: "Dark backgrounds, large type, high-contrast imagery.",
        },
        {
          label: "Route 3",
          title: "Modern Editorial",
          desc: "Dynamic grid layouts, colour accents, visual storytelling.",
        },
      ],
      postApproveMessage: "Design direction selected. Building the full deck now.",
    }),
    phase({
      id: "full-deck",
      progressLabel: "Full Deck",
      entryMessage: "Here is the complete presentation — all slides designed:",
      type: "output",
      generator: "structured",
      inherits: ["design-routes"],
      outputLabel: "Full Presentation Deck",
      refineExamples: [
        "Make slide 4 more visual",
        "Reduce text on slide 3",
        "Change only slide 2",
      ],
      approveLabel: "Approve Presentation",
      postApproveMessage: "Presentation approved. Exporting final files.",
    }),
    phase({
      id: "final",
      progressLabel: "Final",
      entryMessage: "Your presentation is complete and ready to export.",
      type: "final",
      inherits: ["full-deck"],
      finalActions: ["Download PPT", "Download PDF"],
    }),
  ],
};

export const emailersConfig: CdfServiceConfig = {
  serviceId: "emailers",
  service: "Emailers",
  outputMapService: "email",
  briefPlaceholder:
    "e.g. Promotional email for our new mango drink. Offer: 20% off. Audience: existing customers.",
  briefAck:
    "Got it — I've noted the email purpose, audience, offer and brand. Starting with copy routes before design.",
  studioHandoffAfterPhaseId: "email-design",
  phases: [
    phase({
      id: "copy-routes",
      progressLabel: "Copy Routes",
      entryMessage: "Here are 3 communication approaches for this email:",
      type: "routes",
      generator: "launch_routes",
      choiceNoun: "Copy Route",
      selectionStayInChat: true,
      textLines: [
        "Route name + communication angle",
        "Subject / tone approach",
        "Why it fits this audience and offer",
      ],
      postApproveMessage: "Copy route selected. Writing the full email copy now.",
    }),
    phase({
      id: "full-copy",
      progressLabel: "Full Copy",
      entryMessage: "Here is the complete email copy:",
      type: "text-approval",
      generator: "structured",
      inherits: ["copy-routes"],
      textLines: [
        "Subject: [Subject line]",
        "Preview text: [Preview text]",
        "Hero headline: [Main headline]",
        "Body: [Opening · Product message · Benefit]",
        "CTA: [Primary call-to-action]",
        "Footer: [Legal / unsubscribe]",
      ],
      refineExamples: [
        "Make the subject less salesy",
        "Shorten the body copy",
        "Make the CTA more specific",
      ],
      approveLabel: "Approve Copy",
      postApproveMessage: "Copy approved. Defining the email structure before designing.",
    }),
    phase({
      id: "structure",
      progressLabel: "Email Structure",
      entryMessage: "Here is the proposed email structure:",
      type: "text-approval",
      generator: "structured",
      inherits: ["full-copy"],
      textLines: [
        "Header — Logo + nav",
        "Hero — Full-width visual + headline",
        "Main message — Lead copy + benefit",
        "Product/Offer — Image + offer + CTA",
        "Footer — Legal, links, unsubscribe",
      ],
      refineExamples: [
        "Add a second product section",
        "Remove the nav from header",
        "Make the hero shorter",
      ],
      approveLabel: "Approve Structure",
      postApproveMessage: "Structure approved. Designing the full email now.",
    }),
    phase({
      id: "email-design",
      progressLabel: "Email Design",
      entryMessage: "Here is the complete email design:",
      type: "output",
      generator: "structured",
      inherits: ["structure"],
      outputLabel: "Email Design",
      refineExamples: [
        "Make the hero image larger",
        "Increase the CTA button size",
        "Change the background colour",
      ],
      approveLabel: "Approve Design",
      postApproveMessage: "Design approved. Creating desktop and mobile versions.",
    }),
    phase({
      id: "responsive",
      progressLabel: "Responsive",
      entryMessage: "Here are the desktop and mobile versions of the approved email:",
      type: "multi-output",
      generator: "image",
      inherits: ["email-design"],
      outputLabel: "Desktop / Mobile Email",
      refineExamples: ["Adjust mobile spacing", "Make the mobile CTA larger"],
      approveLabel: "Approve Responsive",
      postApproveMessage: "Responsive versions approved. Packaging the final emailer.",
    }),
    phase({
      id: "final",
      progressLabel: "Final",
      entryMessage: "Your emailer is ready.",
      type: "final",
      inherits: ["responsive"],
      finalActions: ["Download Final Emailer"],
    }),
  ],
};

export const webTechConfig: CdfServiceConfig = {
  serviceId: "web-tech",
  service: "Web Tech",
  outputMapService: "website",
  briefPlaceholder:
    "e.g. Build a website for UNAGENCY — a creative services platform. 5 pages, modern and premium.",
  briefAck:
    "Got it — I've noted the business, purpose, audience and required pages. Let me start with a sitemap.",
  studioHandoffAfterPhaseId: "homepage",
  phases: [
    phase({
      id: "sitemap",
      progressLabel: "Sitemap",
      entryMessage: "Here is the proposed sitemap:",
      type: "text-approval",
      generator: "structured",
      textLines: ["Home", "About", "Services", "Work", "Contact"],
      refineExamples: [
        "Add an Industries page",
        "Remove About",
        "Rename Work to Portfolio",
      ],
      approveLabel: "Approve Sitemap",
      postApproveMessage: "Sitemap approved. Here is the page structure for the Homepage.",
    }),
    phase({
      id: "page-structure",
      progressLabel: "Page Structure",
      entryMessage: "Homepage section structure:",
      type: "text-approval",
      generator: "structured",
      inherits: ["sitemap"],
      textLines: [
        "01 — Hero",
        "02 — Brand Introduction",
        "03 — Services",
        "04 — Why Choose Us",
        "05 — Work / Case Studies",
        "06 — Testimonials",
        "07 — CTA",
        "08 — Footer",
      ],
      refineExamples: ["Move Work above Services", "Add a stats bar after the hero"],
      approveLabel: "Approve Page Structure",
      postApproveMessage: "Page structure approved. Generating the wireframe now.",
    }),
    phase({
      id: "wireframe",
      progressLabel: "Wireframe",
      entryMessage:
        "Here is the homepage wireframe — low-detail layout based on the approved structure:",
      type: "text-approval",
      generator: "structured",
      inherits: ["page-structure"],
      textLines: [
        "Hero — headline + primary CTA placement",
        "Brand intro — short copy block",
        "Services — card / list layout",
        "Work — case study grid",
        "CTA + Footer",
      ],
      refineExamples: ["Hero needs to be shorter", "Make the CTA section full-width"],
      approveLabel: "Approve Wireframe",
      postApproveMessage: "Wireframe approved. Here are 3 visual design directions.",
    }),
    phase({
      id: "ui-routes",
      progressLabel: "UI Routes",
      entryMessage: "Here are 3 UI design directions for the site:",
      type: "routes",
      generator: "launch_routes",
      inherits: ["wireframe"],
      choiceNoun: "UI Direction",
      selectionStayInChat: true,
      textLines: [
        "Route name + visual/UI personality",
        "Typography, colour, motion approach",
        "Why it fits this brand and wireframe",
      ],
      postApproveMessage: "Direction selected. Designing the homepage now.",
    }),
    phase({
      id: "homepage",
      progressLabel: "Homepage",
      entryMessage: "Here is the designed homepage:",
      type: "output",
      generator: "image",
      inherits: ["ui-routes"],
      outputLabel: "Homepage Design",
      refineExamples: [
        "Make the hero headline larger",
        "Change the primary colour",
        "Try a different hero layout",
      ],
      approveLabel: "Approve Homepage",
      postApproveMessage: "Homepage approved. Generating remaining pages.",
    }),
    phase({
      id: "remaining-pages",
      progressLabel: "Remaining Pages",
      entryMessage: "Here are the remaining pages built on the approved homepage system:",
      type: "multi-output",
      inherits: ["homepage"],
      outputLabel: "All Pages",
      refineExamples: ["Adjust the About page layout", "Add more visuals to Services"],
      approveLabel: "Approve All Pages",
      postApproveMessage: "All pages approved. Creating responsive versions.",
    }),
    phase({
      id: "responsive",
      progressLabel: "Responsive",
      entryMessage: "Here are mobile and tablet versions of the approved pages:",
      type: "multi-output",
      inherits: ["remaining-pages"],
      outputLabel: "Responsive Layouts",
      refineExamples: ["Tighten mobile nav", "Adjust tablet hero crop"],
      approveLabel: "Approve Responsive",
      postApproveMessage: "Responsive layouts approved. Ready to build or export.",
    }),
    phase({
      id: "final",
      progressLabel: "Final",
      entryMessage: "All pages and responsive versions are complete.",
      type: "final",
      inherits: ["responsive"],
      finalActions: ["Build", "Export Design", "Finalize"],
    }),
  ],
};

export const brandStrategyConfig: CdfServiceConfig = {
  serviceId: "brand-strategy",
  service: "Brand Strategy",
  outputMapService: "strategy",
  briefPlaceholder:
    "e.g. Develop a brand strategy for CrunchO chips. New launch targeting 18-30 in India.",
  briefAck:
    "Brief received. Here are 3 strategic territories before developing the full platform:",
  studioHandoffAfterPhaseId: "brand-platform",
  phases: [
    phase({
      id: "territories",
      progressLabel: "Strategic Territories",
      entryMessage: "Here are 3 strategic brand territories:",
      type: "routes",
      generator: "launch_routes",
      choiceNoun: "Territory",
      selectionStayInChat: true,
      textLines: [
        "Insight",
        "Opportunity",
        "Brand role",
        "Positioning",
        "Benefit",
        "Reason to believe",
      ],
      postApproveMessage: "Territory selected. Developing the full brand platform now.",
    }),
    phase({
      id: "brand-platform",
      progressLabel: "Brand Platform",
      entryMessage: "Here is the brand platform built on the selected territory:",
      type: "text-approval",
      generator: "structured",
      inherits: ["territories"],
      textLines: [
        "Brand Purpose",
        "Positioning",
        "Promise",
        "Personality",
        "Values",
        "Core Audience",
        "Reasons to Believe",
      ],
      refineExamples: [
        "Positioning feels too premium — make it more accessible",
        "Make the promise more emotional",
      ],
      approveLabel: "Approve Brand Platform",
      postApproveMessage: "Platform approved. Developing tone of voice now.",
    }),
    phase({
      id: "tone-of-voice",
      progressLabel: "Tone of Voice",
      entryMessage: "Here is the tone of voice framework:",
      type: "text-approval",
      generator: "structured",
      inherits: ["brand-platform"],
      textLines: [
        "How we speak",
        "Language we use",
        "What we avoid",
        "Example — Social",
        "Example — Pack",
        "Example — Campaign",
      ],
      refineExamples: ["Make the tone less aggressive", "Add more warmth"],
      approveLabel: "Approve Tone of Voice",
      postApproveMessage: "Tone of voice approved. Building the messaging framework now.",
    }),
    phase({
      id: "messaging",
      progressLabel: "Messaging",
      entryMessage: "Here is the messaging framework:",
      type: "text-approval",
      generator: "structured",
      inherits: ["tone-of-voice"],
      textLines: [
        "Master Message",
        "Product Message",
        "Audience Messages",
        "Elevator Pitch",
        "Tagline Territories",
      ],
      refineExamples: [
        "Master message needs more energy",
        "Make the elevator pitch shorter",
      ],
      approveLabel: "Approve Messaging",
      postApproveMessage: "Messaging approved. Compiling full strategy document.",
    }),
    phase({
      id: "final",
      progressLabel: "Final Strategy",
      entryMessage: "Your complete brand strategy is ready.",
      type: "final",
      inherits: ["messaging"],
      finalActions: ["Download Strategy"],
    }),
  ],
};

export const adCampaignsConfig: CdfServiceConfig = {
  serviceId: "ad-campaigns",
  service: "Ad Campaigns",
  outputMapService: "ads",
  briefPlaceholder:
    "e.g. Launch campaign for CrunchO. Audience 18-30 urban. Channels: social, OOH, digital.",
  briefAck:
    "Campaign brief received. Setting the strategic foundation before big ideas:",
  studioHandoffAfterPhaseId: "master-kv",
  phases: [
    phase({
      id: "campaign-strategy",
      progressLabel: "Campaign Strategy",
      entryMessage: "Here is the campaign strategy foundation:",
      type: "text-approval",
      generator: "structured",
      textLines: [
        "Insight",
        "Problem",
        "Opportunity",
        "Single-minded message",
      ],
      refineExamples: [
        "Sharpen the single-minded message",
        "Make the opportunity more concrete",
      ],
      approveLabel: "Approve Strategy",
      postApproveMessage: "Strategy approved. Here are 3 campaign idea routes:",
    }),
    phase({
      id: "big-ideas",
      progressLabel: "Big Idea Routes",
      entryMessage: "Here are 3 campaign routes, each with a distinct big idea:",
      type: "routes",
      generator: "launch_routes",
      inherits: ["campaign-strategy"],
      choiceNoun: "Campaign Idea",
      selectionStayInChat: true,
      textLines: [
        "Insight",
        "Big idea",
        "Headline territory",
        "Visual thought",
        "Extension potential",
      ],
      postApproveMessage: "Campaign idea selected. Developing the full campaign concept now.",
    }),
    phase({
      id: "campaign-development",
      progressLabel: "Campaign Development",
      entryMessage: "Here is the developed campaign concept:",
      type: "text-approval",
      generator: "text",
      inherits: ["big-ideas"],
      textLines: [
        "Campaign Idea",
        "Headline Options",
        "Visual System",
        "Content Behaviour",
        "Channel Possibilities",
        "Campaign Idea Essence",
      ],
      refineExamples: ["Headlines need more impact", "Make the visual system bolder"],
      approveLabel: "Approve Campaign Concept",
      postApproveMessage: "Campaign concept approved. Creating the master key visual now.",
    }),
    phase({
      id: "master-kv",
      progressLabel: "Master KV",
      entryMessage: "Here is the master key visual for the campaign:",
      type: "output",
      inherits: ["campaign-development"],
      outputLabel: "Master Key Visual",
      refineExamples: [
        "Product should be larger",
        "Headline needs more impact",
        "Simplify the composition",
      ],
      approveLabel: "Approve Master KV",
      postApproveMessage: "Master KV approved. Choose channels to extend into.",
    }),
    phase({
      id: "channel-select",
      progressLabel: "Select Channels",
      entryMessage: "Which channels should we extend this campaign into?",
      type: "routes",
      generator: "none",
      inherits: ["master-kv"],
      choiceNoun: "Channel",
      selectionStayInChat: true,
      routes: [
        {
          label: "Social",
          title: "Social",
          desc: "Feed, Stories and social cutdowns.",
        },
        {
          label: "OOH",
          title: "OOH",
          desc: "Billboards, transit and outdoor formats.",
        },
        {
          label: "Digital Display",
          title: "Digital Display",
          desc: "Banner and display adaptations.",
        },
        {
          label: "Print",
          title: "Print",
          desc: "Print and press adaptations.",
        },
        {
          label: "Other",
          title: "Other",
          desc: "Additional or custom channel.",
        },
      ],
      postApproveMessage: "Channels locked. Generating channel executions now.",
    }),
    phase({
      id: "channel-executions",
      progressLabel: "Channel Executions",
      entryMessage: "Here are all channel executions based on the approved master KV:",
      type: "multi-output",
      inherits: ["channel-select"],
      outputLabel: "Campaign Executions",
      refineExamples: ["Adjust the social crop", "Make the OOH execution simpler"],
      approveLabel: "Approve All Executions",
      postApproveMessage: "All channel executions approved. Campaign assets ready.",
    }),
    phase({
      id: "final",
      progressLabel: "Final Campaign",
      entryMessage: "Your complete campaign is ready — master KV and all channel executions.",
      type: "final",
      inherits: ["channel-executions"],
      finalActions: ["Download Campaign Kit", "Request Adaptation"],
    }),
  ],
};

export const logoConfig: CdfServiceConfig = {
  serviceId: "logo",
  service: "Logo",
  outputMapService: "branding",
  briefPlaceholder: "e.g. I need a logo for CrunchO — a fun crispy snacks brand.",
  briefAck:
    "Understood — I've extracted brand cues from your brief. First, pick a logo type (or let me decide):",
  studioHandoffAfterPhaseId: "logo-options",
  phases: [
    phase({
      id: "logo-type",
      progressLabel: "Logo Type",
      entryMessage: "What type of logo should we explore?",
      type: "routes",
      generator: "none",
      choiceNoun: "Logo Type",
      selectionStayInChat: true,
      routes: [
        {
          label: "Wordmark",
          title: "Wordmark",
          desc: "Name-led typography as the primary mark.",
        },
        {
          label: "Lettermark",
          title: "Lettermark",
          desc: "Initials or monogram as the core identity.",
        },
        {
          label: "Icon / Symbol",
          title: "Icon / Symbol",
          desc: "A standalone symbol that can live with or without the name.",
        },
        {
          label: "Wordmark + Symbol",
          title: "Wordmark + Symbol",
          desc: "Combination mark — wordmark locked with a symbol.",
        },
        {
          label: "Typography-led",
          title: "Typography-led",
          desc: "Expressive custom lettering as the brand signature.",
        },
        {
          label: "Monogram",
          title: "Monogram",
          desc: "Interlocking letters forming a compact badge.",
        },
        {
          label: "Abstract Mark",
          title: "Abstract Mark",
          desc: "Non-literal geometric or abstract form.",
        },
        {
          label: "Not Sure",
          title: "Let UNAGENCY Decide",
          desc: "Recommend the strongest logo type from the brief.",
        },
      ],
      postApproveMessage: "Logo type locked. Here are 3 conceptual territories:",
    }),
    phase({
      id: "territories",
      progressLabel: "Logo Territories",
      entryMessage: "Here are 3 logo territories based on your brief:",
      type: "routes",
      generator: "launch_routes",
      inherits: ["logo-type"],
      choiceNoun: "Territory",
      selectionStayInChat: true,
      textLines: ["Thought", "Typography", "Symbol", "Personality"],
      postApproveMessage: "Great territory. Generating multiple logo options now.",
    }),
    phase({
      id: "logo-options",
      progressLabel: "Logo Options",
      entryMessage: "Here are 4 logo options within the selected territory:",
      type: "output",
      inherits: ["territories"],
      outputLabel: "Logo Options",
      refineExamples: [
        "Make the C heavier",
        "Remove the symbol",
        "Try a more compact wordmark",
        "Try it without the tagline",
      ],
      approveLabel: "Approve & Generate Final Versions",
      postApproveMessage: "Selected logo approved. Generating the complete logo system now.",
    }),
    phase({
      id: "logo-system",
      progressLabel: "Logo System",
      entryMessage:
        "Here is your complete logo system — primary, reversed, black, white, and icon versions:",
      type: "multi-output",
      inherits: ["logo-options"],
      outputLabel: "Complete Logo System",
      approveLabel: "Approve Logo System",
      postApproveMessage: "Logo system approved and ready for download.",
    }),
    phase({
      id: "final",
      progressLabel: "Final",
      entryMessage: "Your complete logo system is ready. All formats and colour versions are included.",
      type: "final",
      inherits: ["logo-system"],
      finalActions: ["Download Logo Pack", "View Applications"],
    }),
  ],
};

export const packagingConfig: CdfServiceConfig = {
  serviceId: "packaging",
  service: "Packaging",
  outputMapService: "packaging",
  briefPlaceholder:
    "e.g. Redesign the packaging for CrunchO chips. New launch, flavour: Masala.",
  briefAck:
    "Brief received. Do you have a dieline to upload, or should we work from a standard pack?",
  studioHandoffAfterPhaseId: "front-pack",
  phases: [
    phase({
      id: "dieline",
      progressLabel: "Dieline / Pack",
      entryMessage: "Provide the structural input for this packaging job:",
      type: "routes",
      generator: "none",
      choiceNoun: "Dieline Option",
      selectionStayInChat: true,
      routes: [
        {
          label: "Upload Dieline",
          title: "Upload Dieline",
          desc: "Upload the production dieline for accurate artwork.",
        },
        {
          label: "I Don’t Have One",
          title: "I Don’t Have One",
          desc: "Continue with a standard pack structure for now.",
        },
        {
          label: "Upload Existing Pack",
          title: "Upload Existing Pack",
          desc: "Share an existing pack as reference.",
        },
      ],
      postApproveMessage: "Structural path locked. Here are 3 packaging design routes:",
    }),
    phase({
      id: "routes",
      progressLabel: "Design Routes",
      entryMessage: "Here are 3 packaging design routes:",
      type: "routes",
      generator: "launch_routes",
      inherits: ["dieline"],
      choiceNoun: "Design Route",
      selectionStayInChat: true,
      textLines: [
        "Route name + pack design idea",
        "Hierarchy / colour / product treatment",
        "Why it wins on shelf for this brief",
      ],
      postApproveMessage: "Route selected. Applying the direction to a 3D pack first.",
    }),
    phase({
      id: "3d-direction",
      progressLabel: "3D Direction",
      entryMessage: "Here is the selected route applied to a 3D pack presentation:",
      type: "output",
      generator: "image",
      inherits: ["routes"],
      outputLabel: "3D Direction Mockup",
      refineExamples: ["Show a different angle", "Make the product name clearer on 3D"],
      approveLabel: "Continue",
      postApproveMessage: "3D direction locked. Generating the front pack design now.",
    }),
    phase({
      id: "front-pack",
      progressLabel: "Front Pack",
      entryMessage: "Here is the front pack design:",
      type: "output",
      inherits: ["3d-direction"],
      outputLabel: "Front Pack Design",
      refineExamples: [
        "Make the product name bigger",
        "Move the claim higher",
        "Change the background colour",
      ],
      approveLabel: "Approve Front Pack",
      postApproveMessage: "Front pack approved. Generating the complete packaging now.",
    }),
    phase({
      id: "complete-pack",
      progressLabel: "Complete Pack",
      entryMessage: "Here is the complete packaging — front, back, sides, top and flat view:",
      type: "multi-output",
      inherits: ["front-pack"],
      outputLabel: "Complete Packaging",
      refineExamples: ["Show me the back panel", "Adjust the nutrition panel layout"],
      approveLabel: "Approve Complete Pack",
      postApproveMessage: "Complete pack approved. Generating additional views.",
    }),
    phase({
      id: "views",
      progressLabel: "Pack Views",
      entryMessage: "Here are additional approved pack views:",
      type: "mockup",
      inherits: ["complete-pack"],
      outputLabel: "Pack Views",
      refineExamples: ["Show the back", "Give me a side angle", "Show it on shelf"],
      approveLabel: "Approve Views",
      postApproveMessage: "Views approved. Need SKU adaptations?",
    }),
    phase({
      id: "sku-adaptations",
      progressLabel: "SKU Adaptations",
      entryMessage: "Here are SKU adaptations using the approved pack architecture:",
      type: "multi-output",
      inherits: ["views"],
      outputLabel: "SKU Adaptations",
      refineExamples: ["Adjust flavour name hierarchy", "Match colour coding for SKUs"],
      approveLabel: "Approve SKU Adaptations",
      postApproveMessage: "SKU adaptations approved. Packaging files are ready.",
    }),
    phase({
      id: "final",
      progressLabel: "Final",
      entryMessage: "Your packaging is complete. All views and production files are ready.",
      type: "final",
      inherits: ["sku-adaptations"],
      finalActions: [
        "Download Packaging Files",
        "Download 3D Mockups",
        "Create Another SKU",
      ],
    }),
  ],
};

export const printOohConfig: CdfServiceConfig = {
  serviceId: "print-ooh",
  service: "Print & OOH",
  outputMapService: "print",
  briefPlaceholder:
    "e.g. Create a billboard for CrunchO chips. Size 40×20ft. Message: The new crunch in town.",
  briefAck:
    "Brief received. I've noted the format, dimensions and key message. Confirm size before creative routes:",
  studioHandoffAfterPhaseId: "master-artwork",
  phases: [
    phase({
      id: "format-size",
      progressLabel: "Format / Size",
      entryMessage: "Choose the print/OOH format and size:",
      type: "routes",
      generator: "none",
      choiceNoun: "Format",
      selectionStayInChat: true,
      routes: [
        {
          label: "Enter Size",
          title: "Enter Size",
          desc: "Specify exact dimensions for this artwork.",
        },
        {
          label: "Use Recommended Format",
          title: "Use Recommended Format",
          desc: "Use a recommended print/OOH format from the brief.",
        },
      ],
      postApproveMessage: "Format locked. Here are 3 creative directions:",
    }),
    phase({
      id: "routes",
      progressLabel: "Creative Routes",
      entryMessage: "Here are 3 creative directions for your print/OOH:",
      type: "routes",
      generator: "launch_routes",
      inherits: ["format-size"],
      choiceNoun: "Direction",
      selectionStayInChat: true,
      textLines: [
        "Direction name + visual thought",
        "Headline / product role / composition",
        "Why it fits this format and message",
      ],
      postApproveMessage: "Direction selected. Creating the master artwork now.",
    }),
    phase({
      id: "master-artwork",
      progressLabel: "Master Artwork",
      entryMessage: "Here is the master artwork at the specified dimensions:",
      type: "output",
      inherits: ["routes"],
      outputLabel: "Master Artwork",
      refineExamples: [
        "Make the headline shorter",
        "Make the pack bigger",
        "Increase visibility from distance",
        "Reduce the copy",
      ],
      approveLabel: "Approve Master Artwork",
      postApproveMessage: "Master artwork approved. Adapting to additional formats.",
    }),
    phase({
      id: "adaptations",
      progressLabel: "Format Adaptations",
      entryMessage: "Here are all format adaptations based on the approved master:",
      type: "multi-output",
      inherits: ["master-artwork"],
      outputLabel: "Format Adaptations",
      refineExamples: ["Adjust the newspaper ad crop", "Make the standee taller"],
      approveLabel: "Approve All Formats",
      postApproveMessage: "Running print validation — dimensions, resolution, bleed.",
    }),
    phase({
      id: "validate",
      progressLabel: "Validation",
      entryMessage: "Print validation checklist against the approved master:",
      type: "text-approval",
      generator: "structured",
      inherits: ["adaptations"],
      textLines: [
        "Dimensions match target formats",
        "Resolution / PPI sufficient for print",
        "Safe margins and bleed present",
        "Logo and mandatory copy clear",
      ],
      approveLabel: "Validate Files",
      postApproveMessage: "Validation complete. Final artwork is ready.",
    }),
    phase({
      id: "final",
      progressLabel: "Final",
      entryMessage: "Print validation complete. All files are production-ready.",
      type: "final",
      inherits: ["validate"],
      finalActions: ["Download Final Artwork"],
    }),
  ],
};

export const videosConfig: CdfServiceConfig = {
  serviceId: "videos",
  service: "Videos",
  outputMapService: "video",
  briefPlaceholder: "Describe your video brief...",
  briefAck: "Got it. Do you already have a script, or would you like UNAGENCY to create one?",
  studioHandoffAfterPhaseId: "animation",
  phases: [
    phase({
      id: "script-source",
      progressLabel: "Script Source",
      entryMessage: "Do you already have a script, or should I create one?",
      type: "routes",
      generator: "none",
      choiceNoun: "Script Source",
      selectionStayInChat: true,
      routes: [
        {
          label: "Option 1",
          title: "I Have a Script",
          desc: "Paste or upload your existing script for review.",
        },
        {
          label: "Option 2",
          title: "Create Script",
          desc: "UNAGENCY develops 2–3 script routes from your brief.",
        },
      ],
      postApproveMessage: "Continuing with your script path.",
    }),
    phase({
      id: "script-routes",
      progressLabel: "Script Routes",
      entryMessage: "Here are 3 script routes based on your brief:",
      type: "routes",
      generator: "launch_routes",
      inherits: ["script-source"],
      choiceNoun: "Script Route",
      selectionStayInChat: true,
      textLines: [
        "Script route name + narrative approach",
        "Opening / structure / VO tone",
        "Why it fits this video brief",
      ],
      postApproveMessage: "Writing the full script for the selected route.",
    }),
    phase({
      id: "full-script",
      progressLabel: "Full Script",
      entryMessage: "Here is the complete script:",
      type: "text-approval",
      generator: "text",
      inherits: ["script-routes"],
      textLines: [
        "0–3 sec — Visual + VO",
        "3–6 sec — Visual + VO",
        "6–10 sec — Visual + VO",
        "10–13 sec — Logo lockup + VO",
      ],
      approveLabel: "Approve Script",
      refineExamples: ["Tighten scene 2 VO", "Make the opening more surprising"],
      postApproveMessage: "I'll now create the storyboard based on the approved script.",
    }),
    phase({
      id: "storyboard",
      progressLabel: "Storyboard",
      entryMessage: "Here is the storyboard based on the approved script:",
      type: "multi-output",
      inherits: ["full-script"],
      outputLabel: "Storyboard Frames",
      refineExamples: ["Change frame 3", "Make the product bigger in frame 2"],
      approveLabel: "Approve Storyboard",
      postApproveMessage: "Animating the storyboard now.",
    }),
    phase({
      id: "animation",
      progressLabel: "Animation",
      entryMessage: "Here is a preview of your animated video:",
      type: "output",
      generator: "video",
      inherits: ["storyboard"],
      outputLabel: "Video Preview",
      refineExamples: ["Slow the transition in scene 2", "Request Revision"],
      approveLabel: "Approve Final Video",
      postApproveMessage: "Your final video is ready.",
    }),
    phase({
      id: "final",
      progressLabel: "Final Video",
      entryMessage: "Your final video is ready. Download or request adaptations.",
      type: "final",
      inherits: ["animation"],
      finalActions: ["Download Final Video", "Export / Adapt"],
    }),
  ],
};

export const storeDisplayConfig: CdfServiceConfig = {
  serviceId: "store-display",
  service: "Store Display",
  outputMapService: "pos",
  briefPlaceholder:
    "e.g. Design a wobbler for CrunchO Masala chips. Key message: New Launch.",
  briefAck:
    "Brief noted — I've identified the POSM touchpoint, store context and shopper message. Here are 3 retail creative routes:",
  studioHandoffAfterPhaseId: "posm-design",
  phases: [
    phase({
      id: "routes",
      progressLabel: "Retail Routes",
      entryMessage: "Here are 3 retail creative routes:",
      type: "routes",
      generator: "launch_routes",
      choiceNoun: "Retail Route",
      selectionStayInChat: true,
      textLines: [
        "Route name + retail creative idea",
        "Shelf / shopper attention approach",
        "Why it fits this POSM brief",
      ],
      postApproveMessage: "Route selected. Creating the POSM design now.",
    }),
    phase({
      id: "posm-design",
      progressLabel: "POSM Design",
      entryMessage: "Here is the POSM design for the selected touchpoint:",
      type: "output",
      inherits: ["routes"],
      outputLabel: "POSM Design",
      refineExamples: [
        "Make the claim bigger",
        "Pack needs more visibility",
        "Reduce copy",
        "Change the background",
      ],
      approveLabel: "Approve POSM Design",
      postApproveMessage: "Design approved. Placing it in a realistic store environment now.",
    }),
    phase({
      id: "store-mockup",
      progressLabel: "Store Mockup",
      entryMessage: "Here is the approved design in a relevant retail environment:",
      type: "mockup",
      inherits: ["posm-design"],
      outputLabel: "Store Environment Mockup",
      refineExamples: ["Show it on a different shelf", "Show it at checkout"],
      approveLabel: "Approve Mockup",
      postApproveMessage: "Mockup approved. Creating related POSM family items.",
    }),
    phase({
      id: "posm-family",
      progressLabel: "POSM Family",
      entryMessage: "Here are related POSM touchpoints adapted from the approved system:",
      type: "multi-output",
      inherits: ["store-mockup"],
      outputLabel: "POSM Family",
      refineExamples: ["Adjust the dangler size", "Simplify the shelf strip"],
      approveLabel: "Approve POSM Family",
      postApproveMessage: "POSM family approved. Production files are ready.",
    }),
    phase({
      id: "final",
      progressLabel: "Final",
      entryMessage: "Your store display assets are complete and production-ready.",
      type: "final",
      inherits: ["posm-family"],
      finalActions: ["Download POSM", "Download Mockups"],
    }),
  ],
};

export const merchandiseConfig: CdfServiceConfig = {
  serviceId: "merchandise",
  service: "Merchandise",
  outputMapService: "merchandise",
  briefPlaceholder:
    "e.g. Design a T-shirt and cap for UNAGENCY staff. Modern, minimal. Brand colours: black and yellow.",
  briefAck:
    "Got it — I've noted the merchandise items, use case and print area. Here are 3 design route directions:",
  studioHandoffAfterPhaseId: "artwork",
  phases: [
    phase({
      id: "routes",
      progressLabel: "Design Routes",
      entryMessage: "Here are 3 design directions for your merchandise:",
      type: "routes",
      generator: "launch_routes",
      choiceNoun: "Design Route",
      selectionStayInChat: true,
      textLines: [
        "Route name + merch design idea",
        "Print / graphic approach",
        "Why it fits this item and brand",
      ],
      postApproveMessage: "Direction selected. Creating the artwork first.",
    }),
    phase({
      id: "artwork",
      progressLabel: "Artwork",
      entryMessage: "Here is the merchandise artwork based on the selected direction:",
      type: "output",
      inherits: ["routes"],
      outputLabel: "Merchandise Artwork",
      refineExamples: [
        "Reduce the logo size",
        "Use only the symbol",
        "Make the graphic simpler",
        "Try a different colour way",
      ],
      approveLabel: "Approve Artwork",
      postApproveMessage: "Artwork approved. Applying to the selected merchandise now.",
    }),
    phase({
      id: "product-mockup",
      progressLabel: "Product Mockup",
      entryMessage: "Here is the approved artwork applied to the merchandise:",
      type: "mockup",
      inherits: ["artwork"],
      outputLabel: "Product Mockup",
      refineExamples: [
        "Move design to left chest",
        "Put the graphic on the back",
        "Try it in white on black",
      ],
      approveLabel: "Approve Product Mockup",
      postApproveMessage: "Mockup approved. Confirming placement before production artwork.",
    }),
    phase({
      id: "placement",
      progressLabel: "Placement",
      entryMessage: "Confirm artwork placement on the merchandise:",
      type: "text-approval",
      generator: "structured",
      inherits: ["product-mockup"],
      textLines: [
        "Primary placement (e.g. left chest / full front / back)",
        "Scale relative to print area",
        "Clearance from seams / collar / edges",
        "Secondary placements if any",
      ],
      refineExamples: ["Move to left chest", "Reduce scale by 15%"],
      approveLabel: "Approve Placement",
      postApproveMessage: "Placement approved. Preparing final production artwork.",
    }),
    phase({
      id: "final",
      progressLabel: "Final",
      entryMessage: "Production artwork is complete and ready for the print vendor.",
      type: "final",
      inherits: ["placement"],
      finalActions: ["Download Production Artwork", "Download Mockup"],
    }),
  ],
};

export const illustrationConfig: CdfServiceConfig = {
  serviceId: "illustration",
  service: "Illustration",
  outputMapService: "illustration",
  briefPlaceholder:
    "e.g. Create an illustration of a festive Indian market scene for a food brand's Diwali packaging.",
  briefAck:
    "Brief received — I've noted the subject, scene, purpose and style. Here are 3 illustration style routes:",
  studioHandoffAfterPhaseId: "final-illustration",
  phases: [
    phase({
      id: "style-routes",
      progressLabel: "Style Routes",
      entryMessage: "Here are 3 illustration style directions:",
      type: "routes",
      generator: "launch_routes",
      choiceNoun: "Style",
      selectionStayInChat: true,
      textLines: [
        "Style name + visual language",
        "Detail level / technique / palette",
        "Why it fits this illustration brief",
      ],
      postApproveMessage: "Style selected. Creating a rough composition first.",
    }),
    phase({
      id: "composition",
      progressLabel: "Composition",
      entryMessage: "Here is the rough composition — focus on placement and perspective:",
      type: "output",
      inherits: ["style-routes"],
      outputLabel: "Rough Composition",
      refineExamples: [
        "Move the person to the left",
        "Remove the background building",
        "Make the scene wider",
      ],
      approveLabel: "Approve Composition",
      postApproveMessage: "Composition approved. Adding colour, texture and full detail now.",
    }),
    phase({
      id: "final-illustration",
      progressLabel: "Final Illustration",
      entryMessage: "Here is the completed illustration with full colour and detail:",
      type: "output",
      inherits: ["composition"],
      outputLabel: "Final Illustration",
      refineExamples: [
        "Increase the warmth of the light",
        "Make the central figure more prominent",
        "Adjust the colour of the background",
      ],
      approveLabel: "Approve Illustration",
      postApproveMessage: "Illustration approved and ready for export.",
    }),
    phase({
      id: "final",
      progressLabel: "Final",
      entryMessage: "Your illustration is complete and exported at full resolution.",
      type: "final",
      inherits: ["final-illustration"],
      finalActions: ["Download Illustration"],
    }),
  ],
};

export const productionConfig: CdfServiceConfig = {
  serviceId: "production",
  service: "Production",
  outputMapService: "photography",
  briefPlaceholder:
    "e.g. Adapt this approved Instagram creative to 15 digital sizes for the campaign launch.",
  briefAck:
    "Got it — this is a production job from an approved master. Choose the master asset first.",
  studioHandoffAfterPhaseId: "adaptations",
  phases: [
    phase({
      id: "master-select",
      progressLabel: "Approved Master",
      entryMessage: "Choose the approved creative that adaptations must follow:",
      type: "routes",
      generator: "none",
      choiceNoun: "Master Source",
      selectionStayInChat: true,
      routes: [
        {
          label: "Upload Master",
          title: "Upload Master",
          desc: "Upload the approved master creative to adapt from.",
        },
        {
          label: "Select Existing Asset",
          title: "Select Existing Asset",
          desc: "Pick an existing approved asset from your library.",
        },
      ],
      postApproveMessage: "Master locked. Mapping required output formats now.",
    }),
    phase({
      id: "output-mapping",
      progressLabel: "Output Mapping",
      entryMessage: "Here is the output map based on the master and your brief:",
      type: "text-approval",
      generator: "text",
      inherits: ["master-select"],
      textLines: [
        "Master: Instagram Square (1080×1080)",
        "→ Instagram Story (1080×1920)",
        "→ Facebook Feed (1200×630)",
        "→ LinkedIn Post (1200×627)",
        "→ Display 300×250",
        "→ Display 728×90",
      ],
      refineExamples: [
        "Add a WhatsApp format",
        "Remove the display formats",
        "Add Pinterest vertical",
      ],
      approveLabel: "Approve Output Map",
      postApproveMessage: "Output map approved. Generating all versions from the master now.",
    }),
    phase({
      id: "adaptations",
      progressLabel: "All Versions",
      entryMessage: "Here are all versions generated from the approved master:",
      type: "multi-output",
      inherits: ["output-mapping"],
      outputLabel: "All Adaptations",
      refineExamples: [
        "Make the product 10% larger across all",
        "Change CTA to Shop Now everywhere",
        "Adjust crop on Story formats",
      ],
      approveLabel: "Approve All Versions",
      postApproveMessage: "Bulk changes applied. Running validation against master.",
    }),
    phase({
      id: "validate",
      progressLabel: "Validation",
      entryMessage: "Validation checklist — every output vs approved master and target size:",
      type: "text-approval",
      generator: "structured",
      inherits: ["adaptations"],
      textLines: [
        "Creative elements match the approved master",
        "Dimensions match the output map",
        "Safe areas / crops preserved",
        "CTA and logo legibility across sizes",
      ],
      approveLabel: "Validate",
      postApproveMessage: "Validation complete. Final files are ready.",
    }),
    phase({
      id: "final",
      progressLabel: "Final Files",
      entryMessage: "Validation complete. All versions match the master. Files are ready.",
      type: "final",
      inherits: ["validate"],
      finalActions: ["Download Final Files"],
    }),
  ],
};

export const eventBrandingConfig: CdfServiceConfig = {
  serviceId: "event-branding",
  service: "Event Branding",
  outputMapService: "event",
  briefPlaceholder:
    "e.g. Brand the UNAGENCY Annual Client Summit 2026. Premium corporate event, 500 attendees.",
  briefAck:
    "Event brief received. I've noted the event, audience, venue and applications. Here are 3 event theme routes:",
  studioHandoffAfterPhaseId: "master-identity",
  phases: [
    phase({
      id: "theme-routes",
      progressLabel: "Theme Routes",
      entryMessage: "Here are 3 event theme directions:",
      type: "routes",
      generator: "launch_routes",
      choiceNoun: "Theme",
      selectionStayInChat: true,
      textLines: [
        "Theme thought",
        "Visual direction",
        "Graphic language",
        "Mood",
      ],
      postApproveMessage: "Theme selected. Creating the master event identity now.",
    }),
    phase({
      id: "master-identity",
      progressLabel: "Master Identity",
      entryMessage: "Here is the master event identity — logo, key visual, colour and graphic language:",
      type: "output",
      inherits: ["theme-routes"],
      outputLabel: "Master Event Identity",
      refineExamples: [
        "Make the event identity more premium",
        "Reduce graphic elements",
        "Change the colour temperature",
      ],
      approveLabel: "Approve Master Identity",
      postApproveMessage: "Master identity approved. Choose which touchpoints to generate.",
    }),
    phase({
      id: "select-touchpoints",
      progressLabel: "Select Touchpoints",
      entryMessage: "Which event applications should we generate?",
      type: "routes",
      generator: "none",
      inherits: ["master-identity"],
      choiceNoun: "Touchpoint",
      selectionStayInChat: true,
      routes: [
        {
          label: "Stage",
          title: "Stage",
          desc: "Stage backdrop and on-stage branding.",
        },
        {
          label: "Entry",
          title: "Entry",
          desc: "Entry arch, registration and welcome areas.",
        },
        {
          label: "Badge",
          title: "Badge",
          desc: "Attendee badges and lanyards.",
        },
        {
          label: "Social",
          title: "Social",
          desc: "Event social templates and digital assets.",
        },
        {
          label: "Signage",
          title: "Signage",
          desc: "Wayfinding and venue signage.",
        },
        {
          label: "Other",
          title: "Other",
          desc: "Additional custom touchpoint.",
        },
      ],
      postApproveMessage: "Touchpoints selected. Generating those applications now.",
    }),
    phase({
      id: "touchpoints",
      progressLabel: "Event Touchpoints",
      entryMessage: "Here are the event touchpoints designed on the approved identity system:",
      type: "multi-output",
      inherits: ["select-touchpoints"],
      outputLabel: "Event Touchpoints",
      refineExamples: [
        "Change only the stage design",
        "Make the logo larger on the entry arch",
        "Adjust the badge design",
      ],
      approveLabel: "Approve Touchpoints",
      postApproveMessage: "Touchpoints approved. Generating environmental mockups.",
    }),
    phase({
      id: "env-mockups",
      progressLabel: "Environmental Mockups",
      entryMessage: "Here is how the approved branding appears in the event environment:",
      type: "mockup",
      inherits: ["touchpoints"],
      outputLabel: "Environmental Mockup",
      refineExamples: ["Show the stage view", "Show the registration area"],
      approveLabel: "Approve Environmental Look",
      postApproveMessage: "Environmental look approved. Finalising the complete event kit.",
    }),
    phase({
      id: "final",
      progressLabel: "Final Event Kit",
      entryMessage: "Your complete event branding kit is ready — all touchpoints and production files.",
      type: "final",
      inherits: ["env-mockups"],
      finalActions: ["Download Event Kit", "Download Individual Files"],
    }),
  ],
};

/** Display / id / SERVICE_OUTPUT_MAP slug → config. */

/** Display name → config (matches Choose Service labels). */
export const CDF_SERVICE_CONFIGS: Record<string, CdfServiceConfig> = {
  "Social Media": socialMediaConfig,
  Logo: logoConfig,
  Packaging: packagingConfig,
  "Web Tech": webTechConfig,
  "Print & OOH": printOohConfig,
  Videos: videosConfig,
  Presentation: presentationConfig,
  Emailers: emailersConfig,
  "Store Display": storeDisplayConfig,
  Merchandise: merchandiseConfig,
  Illustration: illustrationConfig,
  Production: productionConfig,
  "Brand Strategy": brandStrategyConfig,
  "Ad Campaigns": adCampaignsConfig,
  "Event Branding": eventBrandingConfig,
};

/** Stable serviceId → config. */
export const CDF_CONFIG_BY_ID: Record<string, CdfServiceConfig> = Object.fromEntries(
  Object.values(CDF_SERVICE_CONFIGS).map((c) => [c.serviceId, c])
);

const ALIASES: Record<string, string> = {
  social: "social-media",
  "social-media": "social-media",
  "social media": "social-media",
  branding: "logo",
  logo: "logo",
  packaging: "packaging",
  website: "web-tech",
  "web-tech": "web-tech",
  "web tech": "web-tech",
  print: "print-ooh",
  "print-ooh": "print-ooh",
  "print & ooh": "print-ooh",
  video: "videos",
  videos: "videos",
  presentations: "presentation",
  presentation: "presentation",
  email: "emailers",
  emailers: "emailers",
  pos: "store-display",
  "store-display": "store-display",
  "store display": "store-display",
  merchandise: "merchandise",
  illustration: "illustration",
  photography: "production",
  production: "production",
  strategy: "brand-strategy",
  "brand-strategy": "brand-strategy",
  "brand strategy": "brand-strategy",
  ads: "ad-campaigns",
  "ad-campaigns": "ad-campaigns",
  "ad campaigns": "ad-campaigns",
  event: "event-branding",
  "event-branding": "event-branding",
  "event branding": "event-branding",
};

export function resolveCdfServiceConfig(
  serviceKey: string
): CdfServiceConfig | undefined {
  const raw = serviceKey.trim();
  if (!raw) return undefined;
  if (CDF_SERVICE_CONFIGS[raw]) return CDF_SERVICE_CONFIGS[raw];
  const byId = CDF_CONFIG_BY_ID[raw];
  if (byId) return byId;
  const alias = ALIASES[raw.toLowerCase()];
  if (alias) return CDF_CONFIG_BY_ID[alias];
  return undefined;
}

export function listCdfServiceIds(): string[] {
  return Object.keys(CDF_CONFIG_BY_ID);
}
