name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Add Bun to PATH
      run: echo 'export PATH=~/.bun/bin:$PATH' >> $GITHUB_ENV
    - name: Clean npm cache
      run: npm cache clean --force
    - run: npm ci
    - name: Start Application with PM2
      run: pm2 start ecosystem.config.js
      env:
        DB_URI: ${{ secrets.DB_URI }}
        PORT: ${{ secrets.PORT }}
        TOKEN: ${{ secrets.TOKEN }}
        apiKey: ${{ secrets.apiKey }}
        authDomain: ${{ secrets.authDomain }}
        projectId: ${{ secrets.projectId }}
        storageBucket: ${{ secrets.storageBucket }}
        messagingSenderId: ${{ secrets.messagingSenderId }}
        appId: ${{ secrets.appId }}
        measurementId: ${{ secrets.measurementId }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        stripe_access_key: ${{ secrets.stripe_access_key }}
        stripe_secret_key: ${{ secrets.stripe_secret_key }}
        stripe_webhook_endpoint_secret: ${{ secrets.stripe_webhook_endpoint_secret }}
    - name: Wait for Application to Start
      run: sleep 10
    - name: Check if Application is Running
      run: curl -I http://localhost:${{ secrets.PORT }}
